### ISSUE TITLE
Example for measurementInvarianceCat() function generates error

### ISSUE THREAD

**Issue by chriscastille6** [yrosseel/lavaan#104]
Hello (and thanks for lavaan!),

When I run the example in the measurementInvarianceCat() function, the following error is generated:
Error in lav_options_set(opt) : 
  lavaan ERROR: estimator ML for ordered data is not supported yet. Use WLSMV instead.

...which is odd because the example defines the estimator as equal to "wlsmv". 

For more context, I'm trying to evaluate the measurement invariance of a model with ordinal indicators (i.e., 5-point Likert scale items).

Thanks in advance!

Chris

**Comment by TDJorgensen** [comment]
`measurementInvarianceCat()` is not a lavaan function, so you should report this on the semTools page:

https://github.com/simsem/semTools

But the example runs fine for me.  Are you using the latest versions of the software?

```
install.packages("lavaan", repos = "http://www.da.ugent.be", type = "source")
devtools::install_github("simsem/semTools/semTools")
```

If you still get the error with lavaan >= 0.6-1 and semTools 0.4-15.930, please post an issue on the semTools github, along with your `sessionInfo()` output so I can see if there are any conflicts.

**Comment by chriscastille6** [comment]
Thanks! I can run the code now. Apologies for posting to the wrong board.

**Comment by chriscastille6** [comment]
Back again. So I'm generating a new error this time and could use some help once more. 

Here is a sample of my code:
mi <- measurementInvarianceCat(initial.cfa, ordered = c("PA1", "PA2", "PA3", "PA4", "PA5", 
                                                        "PA6", "PA7", "PA8", "PA9", "PA10", 
                                                        "NA1", "NA2", "NA3", "NA4", "NA5", 
                                                        "NA6", "NA7", "NA8", "NA9", "NA10", 
                                                        "Mood_T1", "PP1", "PP2", "PP3", "PP4", 
                                                        "PP5", "PP6", "PP7", "PP8", "PP9", 
                                                        "PP10", "VOICE1", "VOICE2", "VOICE3", 
                                                        "VOICE4", "VOICE5", "VOICE6", "TC1", 
                                                        "TC2", "TC3", "TC4", "TC5", "TC6", 
                                                        "TC7", "TC8", "TC9", "TC10", "IRB1",
                                                        "IRB2", "IRB3", "IRB4", "IRB5", "IRB6", 
                                                        "IRB7", "OCBI1", "OCBI2", "OCBI3", "OCBI4", 
                                                        "OCBI5", "OCBI6", "OCBI7", "OCBO1", "OCBO2", 
                                                        "OCBO3", "OCBO4", "OCBO5", "OCBO6", "OCBO7"), 
                               data = data2, group="COND", missing ="ML", parameterization = "theta", estimator = "dwls", information = "expected")

Several errors emerge:
"The following model(s) did not converge: 
fit.configuralfit.loadingsfit.thresholdsfit.means
Error in lavaan::lavTestLRT(...) : 
  argument "object" is missing, with no default
In addition: Warning message:
In lav_data_full(data = data, group = group, cluster = cluster,  :
  lavaan WARNING: some cases are empty and will be ignored:
  94"

I'm trying to interpret these errors. Could you help?

**Comment by TDJorgensen** [comment]
Again, please post problems with this function on the semTools GitHub, not lavaan's GitHub.

As the error message says, your models did not converge.  Perhaps this is because you did not name your `lavaan` argument for the model syntax, so it did not know what model to fit to the data.  Would this resolve the issue?
```
measurementInvarianceCat(model = initial.cfa, ...)
```

**Comment by TDJorgensen** [comment]
FYI, `missing ="ML"` is only available with ML estimation, not when `estimator = "dwls"`.  You could request `missing ="pairwise"`.
