### ISSUE TITLE
Lavaan predict in Python

### ISSUE THREAD

**Issue by DominiqueMakowski** [yrosseel/lavaan#107]
I fitted a Lavan CFA which I use to predict new scores for my participants. I would be interested in opening and using this model for predictions in Python. Is it possible? Thank you :)

**Comment by DominiqueMakowski** [comment]
Ok let's take this example model:
```r
library(lavaan)
names(iris)
model <- '
# regressions
Sepal.Length ~  Sepal.Width + Petal.Length + Petal.Width
'
fit <- sem(model,
           data=iris)
```
(it's very just for illustration I know lavaan would be not needed for this regression)

I would like to save this fit (on my computer) and then, load it in python (without calling R) and exctracting the model's prediction based on new provided values for the predictors.

**Comment by yrosseel** [comment]
What I would suggest is this: save the model-estimated model matrices (lambda, psi, theta, beta, ...) to a set of external files. You can get them from a fitted lavaan object (say, 'fit') (as a named list) as follows:
```
MM <- lavTech(fit, "est")
```
You can save these matrices to a file (using write.table() or whatever you prefer). Then, at the python side, you can read in those matrices, and apply them to compute predicted values.

**Comment by yrosseel** [comment]
As you want to 'predict' factor scores, you may want to have a look at the lav_predict.R file.  Assuming continuous data, you can look at either the lav_predict_eta_normal() function (for 'regression type' factor scores), or the lav_predict_eta_bartlett() function. The formulas are described in many places, one source being:
Devlieger, I., Mayer, A., & Rosseel, Y. (2016). Hypothesis testing using factor score regression: A comparison of four methods. Educational and psychological measurement, 76(5), 741-770.
