### ISSUE TITLE
cfa function with no data argument

### ISSUE THREAD

**Issue by doomlab** [yrosseel/lavaan#111]
Hi guys! I learned something new today teaching with `lavaan` - you can specify a model and no data:

```
> text.model = 'latent =~ V1 + V2 + V3 + V4'
> text.fit = cfa(text.model)
> summary(text.fit)
lavaan 0.6-2 did not run (perhaps do.fit = FALSE)?
** WARNING ** Estimates below are simply the starting values
```

Is there a way to provide a warning after the `cfa` function if the `data` or `sample.cov` arguments are not provided?

**Comment by yrosseel** [comment]
That is by design! So you can provide starting values, and get the model-implied sample statistics. It is also made clear in the summary() output, so I will leave it by that.
