### ISSUE TITLE
Error defining both values and labels for an intercept

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#115]
This is a nuanced one.  In multigroup models, if you want to specify both a vector of labels and a vector of fixed/free values, it returns an error only when the values are specified before the labels.
```
example(cfa)
## works fine
summary(update(fit, add = "x1 ~ c(foo, bar)*1 + c(5, 5)*1", group = "school"))
## same idea, but returns an error
summary(update(fit, add = "x1 ~ c(5, 5)*1 + c(foo, bar)*1", group = "school"))
```
The error indicates that the second label (`bar`, not `foo`) is interpreted as a variable name.

This is not a problem in single-group models, when there is only 1 value and label.  It also does not seem to cause a problem for other types of parameter (`~~` or `=~`).

**Comment by yrosseel** [comment]
Indeed. The problem only occurs with intercepts (~1). I have improved the syntax parser, and this should now work in lavaan dev 0.6-3.1300.
