### ISSUE TITLE
lavTables no longer works on data only

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#116]
The help-page example returns warnings for the data-only examples, and using `str()` shows that the returned value is a `data.frame` with no rows.
```
HS9 <- HolzingerSwineford1939[,c("x1","x2","x3","x4","x5",
                                 "x6","x7","x8","x9")]
HSbinary <- as.data.frame( lapply(HS9, cut, 2, labels=FALSE) )
# using the data only
lavTables(HSbinary, dim = 0L, categorical = names(HSbinary))
lavTables(HSbinary, dim = 1L, categorical = names(HSbinary), stat=c("th.un"))
lavTables(HSbinary, dim = 2L, categorical = names(HSbinary), type = "table")
```
Not sure which version this started being a problem, but it occurs both in the public CRAN version (0.6-2) and the current development version ( 0.6-3.1295).

**Comment by yrosseel** [comment]
Fixed in dev 0.6-3.1301
