### ISSUE TITLE
modindices() fails when conditional.x = TRUE

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#117]
Should this fail when there are `conditional.x` predictors in the model?
```
example(cfa)
modindices(update(fit, add = 'visual ~ ageyr', conditional.x = TRUE))
```
I think the error occurs at line 718 of xxx_lavaan.R (when `lavaan(..., do.fit = FALSE)` is being called by `lav_object_extended()`), but I'm not sure why it occurs.

**Comment by yrosseel** [comment]
Fixed in lavaan dev 0.6-3.1314
