### ISSUE TITLE
sampling.weights argument not saved to @Options slot

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#120]
Because `sampling.weights` is an element in the `lav_options_default()` output, the actual `lavaan(..., sampling.weights=)` argument is not utilized when fitting the model to the full list of data sets within the `lavaanList()` source.  It inadvertently gets overridden with the default `NULL` [here](https://github.com/yrosseel/lavaan/blob/master/R/xxx_lavaanList.R#L103).  And because the `@Data` slot is of course not passed along, the argument ends up being ignored altogether. 

Using `agemo` as weights for a simple toy example:
```
## using lavaan()
example(cfa)
fit.w <- update(fit, sampling.weights = "agemo")
data.frame(parTable(fit)[c("lhs","op","rhs","est")],
           weighted = parTable(fit.w)$est) # estimates are affected

## return original data each time
bootFun <- function() lavaan::HolzingerSwineford1939
## using lavaanList()
set.seed(123)
lst <- cfaList(HS.model, dataFunction = bootFun, ndat = 2)
set.seed(123)
lst.w <- cfaList(HS.model, dataFunction = bootFun, ndat = 2,
                 sampling.weights = "agemo")
## estimates are not affected (both same as "fit" above)
data.frame(lst@ParTableList[[1]][c("lhs","op","rhs","est")],
           weighted = lst.w@ParTableList[[1]]$est)
```
Fixing this will allow `lavaan.mi` objects to incorporate sampling weights.

I think this would also be a problem for the `cluster` element returned by `lav_options_default()`, except that it gets set manually in the `lavaan()` function [here](https://github.com/yrosseel/lavaan/blob/master/R/xxx_lavaan.R#L326).  I added some comments with suggestions to my [pull request](https://github.com/yrosseel/lavaan/pull/118), but did not change it in case you had different ideas.

**Comment by yrosseel** [comment]
You are absolutely right. There should be no overlap between regular arguments (of sem/cfa/lavaan), and lavOptions. So I removed the sampling.weights from lavOptions, together with cluster and even group.
