### ISSUE TITLE
Asymptotic VCOV of newly defined parameters

### ISSUE THREAD

**Issue by jmetzel** [yrosseel/lavaan#126]
Dear Yves,

During lunch break of your multilevel SEM workshop in Kiel, we have talked about the issue of extending the variance-covariance matrix to also include newly defined parameters (i.e., via ":="). 

Here's the corresponding google groups thread.

https://groups.google.com/forum/#!topic/lavaan/skgZRyzqtYM

Sincerely,
Julian

**Comment by yrosseel** [comment]
In lavaan dev 0.6-4.1337 (or higher), lavInspect(fit, "vcov.def.joint")
will return the *joint* variance matrix of both the free parameters and
the defined parameters. For more variations, see ?lavOptions.

To follow up on the example, this is how it is done:

set.seed(1234)
X <- rnorm(100)
M <- 0.5*X + rnorm(100)
Y <- 0.7*M + rnorm(100)
Data <- data.frame(X = X, Y = Y, M = M)
model <- ' # direct effect
              Y ~ c*X
            # mediator
              M ~ a*X
              Y ~ b*M
            # indirect effect (a*b)
              ab := a*b
            # total effect
              total := c + (a*b)'
fit <- sem(model, data = Data)

# first get ordinary vcov
VCOV <- vcov(fit)

# extract free parameters
x <- coef(fit)

# compute jacobian for 'defined parameters'
JAC <- numDeriv:::jacobian(func = fit@Model@def.function, x = x)

# add identity matrix for free parameters
JAC2 <- rbind(diag(nrow = ncol(JAC)), JAC)
VCOV.joint <- JAC2 %*% VCOV %*% t(JAC2)
