### ISSUE TITLE
Vectors of type logical are not treated as binomial in sem()

### ISSUE THREAD

**Issue by haututu** [yrosseel/lavaan#127]
Ran into some trouble where `sem()` was modelling a logical type variable as a continuous variable rather than a binomial variable. When I cast the logical variable to a factor then it worked.

I caught it because it wasnt producing the same results as in `brms()`.

**Comment by TDJorgensen** [comment]
I think this is not a lavaan issue, but an R issue.  `brms` might have its own special behavior, but for linear models, R will coerce a `logical` vector to `numeric` if you use it as an outcome, but it will coerce it to a `factor` if it is a predictor.

```
set.seed(123)
Y <- sample(c(TRUE, FALSE), size = 50, replace = TRUE)
mean(Y)
# treats as numeric: intercept == mean(Y)
lm(Y ~ 1)
# add logical predictor
X <- factor(sample(c(TRUE, FALSE), size = 50, replace = TRUE))
## creates dummy code for TRUE category
lm(Y ~ X)
```

As stated in the [lavaan tutorial](http://lavaan.ugent.be/tutorial/cat.html), to treat a categorical **outcome** as categorical, it should be declared as an `c("ordered","factor")`, but categorical **predictors** should be represented with `numeric` codes.

**Comment by haututu** [comment]
Okay interesting, I wonder if that might cause trouble when people use `lavaan` via tools like JASP.

Anyway it seems this is intended behavior so closing.
