### ISSUE TITLE
lavTestLRT error with ordered outcomes and same df

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#129]
Hi Yves,

`lavTestLRT()` provides a warning when the models have the same *df*, such as these equivalent models:
```
example(cfa) # fix factor loading, or fix factor variance:
fit1 <- cfa(HS.model, data=HolzingerSwineford1939, std.lv = TRUE)
lavTestLRT(fit, fit1)
```

But if the indicators are ordered, then it issues a cryptic error:
```
HS9 <- HolzingerSwineford1939[,c("x1","x2","x3","x4","x5",
                                 "x6","x7","x8","x9")]
HSbinary <- as.data.frame( lapply(HS9, cut, 2, labels=FALSE) )
fitc <- cfa(HS.model, data=HSbinary, ordered=names(HSbinary))
fitc1 <- cfa(HS.model, data=HSbinary, ordered=names(HSbinary), std.lv = TRUE)
lavTestLRT(fitc, fitc1)
```

It occurs in `lav_test_diff_Satorra2000()` when calculating `PAAPAAP`, because just above that all the empty rows of the A matrix are removed.  I assume this happens whenever the *df* are the same, which would be a more informative error message for users, but I'm not sure whether you would want to add a check (e.g., `if (any(dim(A) == 0)) stop("lavaan ERROR: ...")`) on [line 88](https://github.com/yrosseel/lavaan/blob/master/R/lav_test_diff.R#L88) or prevent all the unnecessary computation by checking for equal *df* on [line 21](https://github.com/yrosseel/lavaan/blob/master/R/lav_test_diff.R#L21) (e.g., `if (m == 0) stop("lavaan ERROR: ...")`).

**Comment by yrosseel** [comment]
Fixed in 0.6-4.
