### ISSUE TITLE
EPC switched sign in lavTestScore

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#130]
`lavTestScore()` seems to switch the sign of the EPC compared to `modindices()`, the latter of which returns EPCs of the same sign as the estimates when actually freeing the parameter.

```
HS.model <- '
    visual  =~ x1 + x2 + x3
    textual =~ x4 + x5 + x6
    speed   =~ x7 + x8 + x9
'
newpar <- '
  visual =~ x9
  textual =~ x3
'
fit <- cfa(HS.model, data=HolzingerSwineford1939, std.lv = TRUE)
## free the 2 new parameters
summary(update(fit, add = newpar))
## EPCs are close
modindices(fit, op = "=~")
## EPCs have the opposite signs
lavTestScore(fit, add = newpar, epc = TRUE)
```

I know the source code uses slightly different methods, but the analogous calculations seem consistent in both functions.  So I don't think this is a bug, but I can't figure out why this happens.  Any ideas?

**Comment by yrosseel** [comment]
It would seem that lavTestScore() is using epc = old-new, while modindices is using epc = new-old. I changed the sign in lavTestScore() to be consistent with modindices(), in 0.6-4.

**Comment by TDJorgensen** [comment]
Thanks Yves.  But following that, I'm not sure why this change was made at line 270:
```
#LIST$epv <- LIST$est + LIST$epc
LIST$epv <- LIST$est - LIST$epc # we changed the sign
```
If changing the `epc` truly made it "new - old" (which in my mind is the correct interpretation: a positive value indicates the parameter is expected to increase), that would mean `epc == epv - est`, so the original calculation should now be correct `epv <- epc + est`.

**Comment by yrosseel** [comment]
You are right of course. Fixed it.
