### ISSUE TITLE
lavaan S3 method for summary function no longer works (0.6-3)

### ISSUE THREAD

**Issue by ghost** [yrosseel/lavaan#132]
Previously, I could run `summary(model)`, where model is a lavaan class object, and it would call `lavaan::summary`.

I recently updated my R installation and reinstalled all my packages and this no longer works.  I have to call summary explicitly with `lavaan::summary`.

More interestingly, when searching the documentation, I can't see any compiled help docs for `lavaan::summary`.

Is this being depreciated?  Or is this perhaps a local issue on my machine?

**Comment by yrosseel** [comment]
Nothing has changed on the lavaan side, so perhaps it is a local issue? 

The documentation for lavaan's summary() can be found by typing (in R):
library(lavaan)
class ? lavaan

or

method ? summary("lavaan")

This is because lavaan() returns an S4 object.
