### ISSUE TITLE
`emmeans` integration

### ISSUE THREAD

**Issue by mattansb** [yrosseel/lavaan#133]
It would be great to be able to test contrasts / simple effects / simple slopes and their CIs [`emmeans`](https://cran.r-project.org/package=emmeans) within a specified SEM.

This would require is adding (and exporting) two new functions: `recover_data.lavaan` and `emm_basis.lavaan`. Some more info can be found [here](https://cran.r-project.org/web/packages/emmeans/vignettes/xtending.html), with an argument specifying the expected-means of which DV should be estimated/ tested, allowing for something like this:

````
library(lavaan)
library(emmeans)
model <- ' 
# latent variable definitions
ind60 =~ x1 + x2 + x3
dem60 =~ y1 + a*y2 + b*y3 + c*y4
dem65 =~ y5 + a*y6 + b*y7 + c*y8

# regressions
dem60 ~ ind60
dem65 ~ ind60 + dem60

# residual correlations
y1 ~~ y5
y2 ~~ y4 + y6
y3 ~~ y7
y4 ~~ y8
y6 ~~ y8
'

fit <- sem(model, data=PoliticalDemocracy)
emmeans(fit, ~ind60, lav.DV = "dem60")
emmeans(fit, ~dem60, lav.DV = "dem65")
````

Please consider - and thanks for this amazing package!

**Comment by TDJorgensen** [comment]
This was already on my to-do list for the `semTools` package, thanks!  I'll have time to look over your source code in March.  I'll be in touch about adding the support there (unless Yves prefers to put it directly into `lavaan`).

**Comment by mattansb** [comment]
Awesome!
(Not *my* source code - I'm just a user of both `lavaan` and `emmean` and thought it would be useful if they were integrated)

**Comment by mattansb** [comment]
Hi @TDJorgensen ! Any news on this front??

**Comment by TDJorgensen** [comment]
No, this is super-low priority for semTools, so by "some time" I meant on the order of years before I would have the free time to figure out how to get around the fact that `recover_data()` and `emm_basis()` methods were not designed with something like a lavaan object in mind.

**Comment by yrosseel** [comment]
This is now under development in semTools. See https://github.com/simsem/semTools/issues/69
