### ISSUE TITLE
A BUGGGGGG of argument 'forcePD' in 'lavaan:::lav_model_objective' 

### ISSUE THREAD

**Issue by tomcat123a** [yrosseel/lavaan#134]
Dear lavaan developers,
I have a question about the internal function  'lavaan:::lav_model_objective' defined in the file 'lav_model_objective.R' in the package source code.
The argument 'forcePD' seems to exist no where in the definition of the function.
I guess this argument will be utilized in future version of lavaan.
Best,
Yilun Zhang

**Comment by yrosseel** [comment]
This was a left-over from old 'solutions' that are no longer used. I have now removed all the (unused) forcePD=  arguments.
