### ISSUE TITLE
automatic setting of intercepts in multilevel multigroup models

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#137]
Messing around, found out that multigroup syntax in MSEM is only possible by defining blocks for each group--level combination (vectors of parameter values/labels within level-specific models return an error).  I tried groups within blocks and vice versa, and saw a difference I don't think is intentional, but perhaps I should be specifying both the group and level before each model.

```
Galo <- read.table("https://users.ugent.be/~yrosseel/lavaan/kiel2018/Galo.dat")
names(Galo) <- c("school", "sex", "galo", "advice", "feduc", "meduc",
                 "focc", "denom")
Galo[Galo == 999] <- NA
Galo$denom1 <- ifelse(Galo$denom == 1, 1, 0)
Galo$denom2 <- ifelse(Galo$denom == 2, 1, 0)
Galo$g <- ifelse(Galo$school < 30, "foo", "bar") # randomly assign schools to groups

G.in.L <- ' level: within
group: foo
  galo ~ focc
group: bar
  galo ~ focc

level: between
  group: foo
    galo ~ focc
  group: bar
    galo ~ focc
'

L.in.G <- ' group: foo
  level: within
    galo ~ focc
  level: between
    galo ~ focc

group: bar
  level: within
    galo ~ focc
  level: between
    galo ~ focc
'

library(lavaan)
fit.G.in.L <- sem(G.in.L, data = Galo, cluster = "school", fixed.x = FALSE,
                  missing = "fiml", std.lv = TRUE, h1 = TRUE)
fit.L.in.G <- sem(L.in.G, data = Galo, cluster = "school", fixed.x = FALSE,
                  missing = "fiml", std.lv = TRUE, h1 = TRUE, group = "g")
```

The first model yields intercepts automatically fixed to zero at both levels within Group 1, whereas the second model yields (appropriately) intercepts fixed to zero at Level 1 within both groups.

**Comment by yrosseel** [comment]
The G.in.L model is illegal: lavaan only supports levels within groups (as the groups must be independent). A check has been added, and this now results in an error in 0.6-4.
