### ISSUE TITLE
Error when estimating latent variable scores

### ISSUE THREAD

**Issue by JacopoCerri** [yrosseel/lavaan#139]
Der all,

I am fitting a structural equation model for dichotomous indicator variables. The model seems to be perfectly fine, both in terms of identification as well as in terms of goodness of fit.
However, when I try to estimate latent variable scores I am having some troubles.

```
> preds <- lavPredict(semlatb, type="lv")
> Error in optim(par = START, fn = f.eta.i, gr = NULL, control = list(reltol = 1e-08,  : 
>   initial value in 'vmmin' is not finite
```
I suspect it might be an issue with maximum likelihood estimation. Do you have any idea why this might be happening? Any idea on how to improve it?

Kind regards,

Jacopo Cerri

**Comment by TDJorgensen** [comment]
> I suspect it might be an issue with maximum likelihood estimation

According to the `?lavPredict` help page, the default method is EBM.  Do you also get a warning when you try `lavPredict(semlatb, method="ML")`?

**Comment by JacopoCerri** [comment]
Yes. It keeps giving me error. May I share some code?

Jacopo

**Comment by TDJorgensen** [comment]
> May I share some code?

Preferably with enough data for Yves to the reproduce error.  I'm not having trouble in my example below, but I'm using the latest development version.  Make sure the errors still occur after installing this:

```
install.packages("lavaan", repos = "http://www.da.ugent.be", type = "source")
library(lavaan) # 0.6-4.1371

HS9 <- HolzingerSwineford1939[,c("x1","x2","x3","x4","x5",
                                 "x6","x7","x8","x9")]
HSbinary <- as.data.frame( lapply(HS9, cut, 2, labels=FALSE) )
HS.model <- ' visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '
fit <- cfa(HS.model, data=HSbinary, ordered=names(HSbinary))

head(lavPredict(fit)) # default is EBM
head(lavPredict(fit, method = "ML"))
```

**Comment by yrosseel** [comment]
Jacopo,

Could you give me a reproducible example? (including data). I wouldlike to study this in more detail. Do you get the same problem with the option optim.method = "nlminb"?

**Comment by JacopoCerri** [comment]
Hi,

I am sorry for my late reply, but I was adopting that approach for some analyses that were completely changed in their approach (and I forgot about them). Find attached a .csv dataset, which explores a SEM where latitude is a latent variable with corresponds to a single observed one, and its effect over a latent variable representing a guild of fish species.

`
semb <- '
#measurement model
guild =~ NA*spA + spB + spC + spD + spE
latitude =~ NA*Lat

#residual correlations
Lat~~0*Lat
spA~~spE
spA~~spB
spC~~spB
spE~~spB
spB~~spD

#regression
guild~latitude
'
semlatb <- sem(semb, data=foo, std.lv=TRUE, std.ov=TRUE, estimator="WLSMV",
               ordered=c("spA", "spB", "spC", "spD", "spE"))
summary(semlatb)

fitmeasures(semlatb)
fitmeasures (semlatb, c("fmin", "chisq", "df", "pvalue"))#Non-significant chisq:fine
fitmeasures (semlatb, c("cfi"))#CFI: close to 1 (0.97), fine
fitmeasures (semlatb, c("tli"))#CFI: close to 1 (0.94), fine
fitmeasures (semlatb, c("rmsea","rmsea.ci.lower", "rmsea.ci.upper",
                        "rmsea.pvalue"))#RMSEA smaller than 0.05 and non-significant: close-fitting
fitmeasures (semlatb, c("gfi"))#GFI close to 1 (0.98), fine
fitmeasures (semlatb,c("srmr", "rmr", "srmr_nomean", "rmr_nomean"))#SRMR close to 0.05, good
residuals(semlatb, type="cor") #Only correlations available for DWLS models
residuals(semlatb)$cov #Only correlations available for DWLS models

inspect(semlatb, what="std")$lambda[,1]^2#Communality
1-(inspect(semlatb, what="std")$lambda[,1]^2) #Uniqueness
inspect(semlatb, what="r2")

range(df$Lat)
preds <- lavPredict(semlatb, type="lv", method="ML")
`



[ExampleLavaanGitHub.csv.zip](https://github.com/yrosseel/lavaan/files/3347190/ExampleLavaanGitHub.csv.zip)


Thanks,

Jacopo Cerri

**Comment by yrosseel** [comment]
Thanks, this helped.
It turns out the error was caused by a zero diagonal element in THETA, due to this line:
Lat ~~ 0*Lat
This will now throw an error in 0.6-4. In your syntax, you either must change '0' by a small number (say, 0.001), or remove the latent variable altogether, and replace it by the observed variable 'Lat'.

**Comment by JacopoCerri** [comment]
Ah, ok. Thanks!

Jacopo
