### ISSUE TITLE
Lavaan no longer available in R version 3.3.3?

### ISSUE THREAD

**Issue by tchichekian** [yrosseel/lavaan#141]
Can anyone help?

Warning in install.packages :
  package ‘lavaan’ is not available (for R version 3.3.3)

**Comment by TDJorgensen** [comment]
You need to install at least R 3.4 (the current version is 3.6)

https://github.com/yrosseel/lavaan/blob/master/DESCRIPTION#L47

**Comment by tchichekian** [comment]
Thank you, I will try that!
