### ISSUE TITLE
lavaanList fails when categorical variable contains NA

### ISSUE THREAD

**Issue by zubekj** [yrosseel/lavaan#145]
Hello,

I encountered a strange behavior of lavaanList function: it does not fit any model when there is a categorical variable with NA values present in the data set. lavaan function works just fine in the same situation.

Code to reproduce:
```
library(lavaan)

data <- list(data.frame(a=ordered(c(NA,0,0,0,1,1,1))))
model <- "a | t1"

# Fits the model normally
fit1 <- lavaan(model, data[[1]])
summary(fit1)

# Fails with: FAILED: nlev too low for some vars
fit2 <- lavaanList(model, data, show.progress=TRUE)
summary(fit2)
```

As far as I understand, there is a check in lavaanList whether factors in all data sets have the same number of levels, and it is being confused by NA values.

**Comment by yrosseel** [comment]
Thanks. Fixed now in dev 0.6-4.
