### ISSUE TITLE
modindices() can fail for MLSEMs with (in)equality constraints and non-integer level.labels

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#149]
OK, bear with me, this is a weird one, but it should be an easy fix.  This error only seems to occur in this combination:

- non-integer labels for the "Level:" blocks in the syntax
- model syntax constrains parameters *or* defines new ones

```
model.num.eq <- '
    level: 1
        fw =~ y1 + L2*y2 + y3
        fw ~ x1 + x2 + x3
    level: 2
        fb =~ y1 + L2*y2 + y3
        fb ~ w1 + w2
'
modindices(fit.num.eq <- sem(model.num.eq, data = Demo.twolevel, cluster = "cluster"))
# fine

model.char.free <- '
    level: student
        fw =~ y1 + L2w*y2 + y3
        fw ~ x1 + x2 + x3
    level: school
        fb =~ y1 + L2b*y2 + y3
        fb ~ w1 + w2
'
modindices(fit.char.free <- sem(model.char.free, data = Demo.twolevel, cluster = "cluster"))
# fine

model.char.eq <- '
    level: student
        fw =~ y1 + L2*y2 +y3
        fw ~ x1 + x2 + x3
    level: school
        fb =~ y1 + L2*y2 + y3
        fb ~ w1 + w2
'
modindices(fit.char.eq <- sem(model.char.eq, data = Demo.twolevel, cluster = "cluster"))
# Error in lavsamplestats@YLp[[g]][[l]] : subscript out of bounds

model.user.def <- '
    level: student
        fw =~ y1 + L2w*y2 +y3
        fw ~ x1 + x2 + x3
    level: school
        fb =~ y1 + L2b*y2 + y3
        fb ~ w1 + w2

L2diff := L2w - L2b
'
modindices(fit.user.def <- sem(model.user.def, data = Demo.twolevel, cluster = "cluster"))
# Error in lavsamplestats@YLp[[g]][[l]] : subscript out of bounds
```

The error occurs when `modindices()` calls `lav_object_extended()` and fits the model to the extended parameter table, which includes rows with operators that are not for parameters (`c("==","<",">",":=")`).  For these, the "level" vector of the parameter table is 0.  That seems to work fine when the syntax defines blocks using integers, but when they are character strings, the zero is now a unique label that gets recognized as `level=="0"` by `lav_partable_level_values()` and `lav_partable_nlevels()`.  That causes the failure when `lav_start()` tries to extract `@YLp` information from this "third" level.

Perhaps the `$level` vector in parameter tables should remain integer, like `$group` and `$block`, and labels can be accessed from `@Data@level.label` whenever needed (and perhaps add a `lav[List]Inspect(fit, "level.label")` option).  But currently, lavaan does not seem to keep the user's level labels in that slot:

```
fit.user.def@Data@level.label
[1] "within"  "cluster"
# should be "student" and "school"
```

Alternatively, the `lav_partable_*` functions could ignore `$level` values corresponding to `$op %in% c("==","<",">",":=")`.

**Comment by yrosseel** [comment]
These are two bugs (or at least oversights) at once: 

1) lav_partable_merge() was adding '0' to the (character) level column, while it should have added character(0) instead, and 

2) lav_partable_nlevels() (and friends) should simply ignore any rows where op %in% c("==", "<", ">", ":=").

Both issues fixed in dev 0.6-5.1452.
