### ISSUE TITLE
wrong names assigned to level-1 factors in second group

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#153]
In a multigroup MLSEM, it looks like the names of factor scores from `lavPredict()` are incorrectly assigned, at least for level-1 variables.  I can't find the location where they are named, so depending on the problem, level-2 names might also be a problem in other scenarios.

```
data(Demo.twolevel)
Demo.twolevel$g <- ifelse(Demo.twolevel$cluster %% 2L, "foo", "bar") # arbitrary groups
table(Demo.twolevel$g)
model <- ' group: foo
level: within
  fw =~ y1 + L2*y2 + L3*y3
  fw ~ x1 + x2 + x3
level: between
  fb =~ y1 + L2*y2 + L3*y3
  fb ~ w1 + w2

group: bar

level: within
  fw =~ y1 + L2*y2 + L3*y3
  fw ~ x1 + x2 + x3
level: between
  fb =~ y1 + L2*y2 + L3*y3
  fb ~ w1 + w2
'
fit <- sem(model, data = Demo.twolevel, cluster = "cluster", group = "g")

FS1 <- lavPredict(fit, acov = "standard")
str(FS1) # INCORRECT: factor should be "fw" in both groups

FS2 <- lavPredict(fit, level = 2L, acov = "standard")
str(FS2) # CORRECT: factor is "fb" in both groups
```
Notice also that the dimension names are incorrectly labeled `"fb"` for the level-1 `"se"` and `"acov"` attributes, only in the second group (but the first group has no labels at all).

**Comment by yrosseel** [comment]
Fixed in 0.6-5
