### ISSUE TITLE
lavPredict(..., append.data = TRUE) error for multigroup MLSEMs

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#157]
It looks like this error occurs because in multigroup MLSEMs, the `@Data@ov.names` slot is still length `ngroups` (or `nlevels`?) instead of `nblocks`.  

```
data(Demo.twolevel)
Demo.twolevel$g <- ifelse(Demo.twolevel$cluster %% 2L, "foo", "bar") # arbitrary groups
table(Demo.twolevel$g)
model <- ' group: foo
level: within
  fw =~ y1 + L2*y2 + L3*y3
  fw ~ x1 + x2 + x3
level: between
  fb =~ y1 + L2*y2 + L3*y3
  fb ~ w1 + w2

group: bar

level: within
  fw =~ y1 + L2*y2 + L3*y3
  fw ~ x1 + x2 + x3
level: between
  fb =~ y1 + L2*y2 + L3*y3
  fb ~ w1 + w2
'
fit <- sem(model, data = Demo.twolevel, cluster = "cluster", group = "g")
lavPredict(fit, append.data = TRUE) # ERROR: ov.names[[gg]] : subscript out of bounds
```

If this is intentional, I think it is easily fixed by changing 

https://github.com/yrosseel/lavaan/blob/master/R/lav_predict.R#L222 

from `ov.names[[gg]]` to `ov.names[[g]]`, which would append all observed variables measured at both levels. 

Also, perhaps you want to add a check and informative error that `append.data=` will be set FALSE when `level = 2`, to prevent this less-informative error:

```
lavPredict(fit, level = 2, append.data = TRUE)
## Error in cbind(out[[g]], data.obs[[g]]) : 
##  number of rows of matrices must match (see arg 2)
```

**Comment by yrosseel** [comment]
Fixed!
