### ISSUE TITLE
no pvalue in parameterEstimates

### ISSUE THREAD

**Issue by perlus** [yrosseel/lavaan#159]
Dear Terrence,
with pleasure have I been using lavaan and semtools. Again thank you so so much for creating and maintaining the code. And thank you so much for your help in the past.

I am now confronted with the problem, that parameter estimates does not output the pvalue for the correlations among my simple cfa. It also does not seem to find zstats. Which might be the problem in the first place? There is no error when I use this line:

parameterEstimates(KFAB2_impRun,pvalue=TRUE, standardized=TRUE)

I just get the columns  "lhs op  rhs std.lv std.all std.nox".

For the environment: I am fitting a four factor model, with missing data and a non normal distribution. Thus I am using the robust ML (MLM) estimator in conjunction with run.mi.

If there is any further information needed, I will be glad to provide it.

If there is another way to get pvalues for factor correlations I would be glad if you could help too.

Kind regards from the heart of Germany, Brunswick,
Alex

**Comment by TDJorgensen** [comment]
See `?standardizedSolution`

**Comment by perlus** [comment]
Hey Terrence, thank you, for your quick response. Unfortunatelly standardizedSolution([myfittedObject],type="std.all",pvalue=TRUE) does not output pvalues either.

**Comment by TDJorgensen** [comment]
The help-page example works fine in version 0.6-5
```
example(standardizedSolution)
```
All the *p* values in this example are too small to be printed as anything but zero, but the `pvalue` column is still there.  If the `pvalue` column is not appearing at all for your data, you would need to post (or privately send us) your data and script for us to reproduce the problem.

**Comment by perlus** [comment]
Unfortunatelly I don't get the column "pvalues" at all, as well as z-values.

Thank you so much for your offer. Where should I send the data and script to?

**Comment by TDJorgensen** [comment]
You can email them to me.  I'm the second `person()` listed here:

https://github.com/yrosseel/lavaan/blob/master/DESCRIPTION

**Comment by TDJorgensen** [comment]
You never mentioned you were analyzing multiple imputations.  This thread should be on the semTools page because you are using `cfa.mi()` output, not `cfa()` output.  There is no semTools routine for calculating *SE*s and *z* tests for the standardized solution of a `lavaan.mi` object, and I do not plan to write one anytime soon.

**Comment by perlus** [comment]
Just realized I am not getting notifications when there are answers on active threads.

Sorry for the late answer.

I am sorry Terrence for your time used. I think I hadn't made it clear in my initial message.

Thank you for checking my problem.
