### ISSUE TITLE
Unexpected behavior in mplus2lavaan.modelSyntax

### ISSUE THREAD

**Issue by cjvanlissa** [yrosseel/lavaan#166]
The function `mplus2lavaan.modelSyntax` unexpectedly does not convert syntax for means:

```
out <- "bfi BY bfi_1*1 (lab1);\nbfi BY bfi_2*1 (lab2);\nbfi BY bfi_3*1 (lab3);\nbfi BY bfi_4*1 (lab4);\nbfi BY bfi_5*1 (lab5);\n[bfi@0] (lab6);\nbfi@1 (lab7);"
mplus2lavaan.modelSyntax(out)
"bfi =~ lab1*start(1)*bfi_1\nbfi =~ lab2*start(1)*bfi_2\nbfi =~ lab3*start(1)*bfi_3\nbfi =~ lab4*start(1)*bfi_4\nbfi =~ lab5*start(1)*bfi_5\n0 ~ lab6*1\nbfi ~~ lab7*1*bfi"
```

Just to clarify: The unexpected bit is this syntax, `0 ~ lab6*1`, which is not correct syntax for means.

**Comment by TDJorgensen** [comment]
There is a lot more wrong than just that.  It looks like `mplus2lavaan.modelSyntax()` somehow recognizes the fixed value in place of the name of the variable.  Probably related to the other mistakes in the generated lavaan syntax:

- simultaneously assigns a fixed value and label to the factor variance
- simultaneously assigns labels and starting values to the loadings

```
> cat(mplus2lavaan.modelSyntax(out))
bfi =~ lab1*start(1)*bfi_1   # should be bfi =~ 1?bfi_1 + lab1*bfi_1
bfi =~ lab2*start(1)*bfi_2   # should be bfi =~ 1?bfi_2 + lab2*bfi_2
bfi =~ lab3*start(1)*bfi_3   # should be bfi =~ 1?bfi_3 + lab3*bfi_3
bfi =~ lab4*start(1)*bfi_4   # should be bfi =~ 1?bfi_4 + lab4*bfi_4
bfi =~ lab5*start(1)*bfi_5   # should be bfi =~ 1?bfi_5 + lab5*bfi_5
0 ~ lab6*1                   # should be bfi ~ 0*1 + lab6*1
bfi ~~ lab7*1*bfi            # should be bfi ~~ 1*bfi + lab7*bfi
```

It seems to work as expected if you only specify either the fixed/starting values or the labels, not both (which I suppose is why the help-page example works).
```
out.labels <- '
bfi BY bfi_1 (lab1);
bfi BY bfi_2 (lab2);
bfi BY bfi_3 (lab3);
bfi BY bfi_4 (lab4);
bfi BY bfi_5 (lab5);
[bfi] (lab6);
bfi (lab7);
'
cat(mplus2lavaan.modelSyntax(out.labels))

out.values <- '
bfi BY bfi_1*1;
bfi BY bfi_2*1;
bfi BY bfi_3*1;
bfi BY bfi_4*1;
bfi BY bfi_5*1;
[bfi@0] ;
bfi@1;
'
cat(mplus2lavaan.modelSyntax(out.values))
```
Not sure how long ago @michaelhallquist wrote this function, but I'm not savvy enough with regular expressions to attempt fixing this bug.

**Comment by cjvanlissa** [comment]
Alright thanks! I'm quite good with regex, but not familiar enough with lavaan syntax to catch all contingencies, and I've already made a workaround for my application. If you ever want this fixed, I'd be willing to help - but for now I'll shelve it!

**Comment by yrosseel** [comment]
Fixed, closing.
