### ISSUE TITLE
MML failure: Error in DD$nu[num.idx, , drop = FALSE] : subscript out of bounds

### ISSUE THREAD

**Issue by the-sushi** [yrosseel/lavaan#168]
When trying to estimate a model with latent/structured residuals as follows:
```
z =~ 1*x1 + 1*x2 + 1*x3

lx1 =~ 1*x1
lx2 =~ 1*x2
lx3 =~ 1*x3

z ~~ z
lx1 ~~ lx1
lx2 ~~ lx2
lx3 ~~ lx3
```

lavaan() with estimator="MML" yields `Error in DD$nu[num.idx, , drop = FALSE] : subscript out of bounds`, while all other estimators work fine.

Example code:
```
library(lavaan)

set.seed(123)

z <- rnorm(500)

x1 <- rnorm(500) + z
x2 <- rnorm(500) + z
x3 <- rnorm(500) + z

df = data.frame(x1, x2, x3)

lav_model <- '
z =~ 1*x1 + 1*x2 + 1*x3

lx1 =~ 1*x1
lx2 =~ 1*x2
lx3 =~ 1*x3

z ~~ z
lx1 ~~ lx1
lx2 ~~ lx2
lx3 ~~ lx3
'

lavaan(lav_model, data=df, estimator="ML")  # works
lavaan(lav_model, data=df, estimator="WLS") # works
lavaan(lav_model, data=df, estimator="GLS") # works
lavaan(lav_model, data=df, estimator="ULS") # works
lavaan(lav_model, data=df, estimator="MML") # Error in DD$nu[num.idx, , drop = FALSE] : subscript out of bounds
```

**Comment by TDJorgensen** [comment]
Why are you using MML?  MML is used for IRT models, so lavaan's experimental implementation is only relevant for models with categorical outcomes.  Yours are continuous.

**Comment by the-sushi** [comment]
@TDJorgensen No really practical reason, just wanted equivalency across lavaan and a separate MML thing and came across this

**Comment by yrosseel** [comment]
It turns out that only meanstructure = TRUE was needed to make it work. This will now be added by default in 0.6-6
