### ISSUE TITLE
lavParseModelString() catches "in" only as variable, not parameter

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#170]
`lavParseModelString()` returns an informative error when it detects `in` as a variable name, but not when it is used as parameter label.

```
lavaanify('in =~ foo') # informative error
lavaanify('foo =~ in*bar') # <text>:1:3: unexpected 'in'
```

**Comment by yrosseel** [comment]
Fixed in dev 0.6-6.1528
