### ISSUE TITLE
Error in as.list(LIST) : object 'LIST' not found

### ISSUE THREAD

**Issue by gamons** [yrosseel/lavaan#171]
Hi all, I could not run (multilevel) model, using the codes below, kept getting "Error in as.list(LIST) : object 'LIST' not found". Please advise.

![Capture8](https://user-images.githubusercontent.com/40445814/73621519-ff2e7800-4668-11ea-82af-5c1b7d6c04b0.JPG)
![Capture10](https://user-images.githubusercontent.com/40445814/73621589-3ac94200-4669-11ea-9043-431a594b0147.JPG)

library(lavaan)
model <- '
level: 1
y1 ˜˜ y1
level: 2
y1 ˜˜ y1
'

fit <- sem(model,
           data = Demo.twolevel,
           cluster = "cluster")

Error in as.list(LIST) : object 'LIST' not found

**Comment by yrosseel** [comment]
This is most likely a copy/paste problem:

The syntax below gives you trouble:

model <- '
level: 1
y1 ˜˜ y1
level: 2
y1 ˜˜ y1
'

but this one will work:

model <- '
   level: 1
     y1 ~~ y1
   level: 2
     y1 ~~ y1
'

Not the spaces matter, but the tilde ("~"). In your upper script, it is 
the 'wrong' tilde ("˜"). The second one contains the correct tilde ("~").

**Comment by yrosseel** [comment]
In lavaan 0.6-6.1517, the 'wrong' tilde is automatically converted to the 'right' tilde.
