### ISSUE TITLE
How to include both latent variables and random effects in the structural equation model

### ISSUE THREAD

**Issue by yixiaoxia0811** [yrosseel/lavaan#172]
I have some ecological data from several different forest sites, i want to make a structural equation model both include a latent variable and random effect （site），how can i do that ？

**Comment by andreaphsz** [comment]
You should use the multilevel modeling approach [http://lavaan.ugent.be/tutorial/multilevel.html](http://lavaan.ugent.be/tutorial/multilevel.html) .

**Comment by yrosseel** [comment]
Not an issue, more a question for the lavaan discussion forum. Closing.
