### ISSUE TITLE
How to deal with multilevel SEM 

### ISSUE THREAD

**Issue by yixiaoxia0811** [yrosseel/lavaan#173]
My data consists of seven variables: productivity(forest productivity), shannon (forest diversity), LAI (leaf area index), com (complexity), entropy (an index indicating forest complexity), height.sd (SD of crown height in a forest), disturbance (human disturbance level of each plot forest plot). Com is a latent variable measured by two variables: entropy and height.sd, all the data come from 16 samples in 9 different forest plots, so the plot is treated as a random effects. My aim is to estimate how diversity, disturbance, LAI and forest complexity directly and indirectly affect forest productivity. 

I assume disturbance has an effect on LAI, shannon and forest complexity (com + LAI + shannon ~ disturbance), and forest diversity has effect on complexity and LAI (com + LAI ~ Shannon), forest complexity depends on the amount of LAI (com ~ LAI); forest complexity can be represented by entropy and height.sd (com=~entropy+height.sd), and finally forest productivity is determined by forest complexity, diversity, LAI and disturbance (productivity ~ com + LAI + shannon + disturbance). 

To solve the problem of both latent variables and random effects, I’am trying to estimate a model with multilevel SEM in lavaan as follows, because I do not have a model for level 2, so I specify a saturated level by adding all variances and covariances of the endogenous variables (here: NPP, entropy and height.sd).

model <- '
  level: 1
com=~entropy+height.sd
productivity ~ com + LAI + shannon + disturbance
com + LAI ~ shannon
com + LAI + shannon ~ disturbance
com ~ LAI
level: 2
productivity ~~ productivity + entropy + height.sd
Entropy ~~ entropy + height.sd
height.sd ~~ height.sd
'
fit <- sem(model = model, data = data1, cluster = "plot")

The results show a warning, how can I solve the problem?

###Warning message:
In lav_data_full(data = data, group = group, cluster = cluster,  :
  lavaan WARNING:
    Level-1 variable “disturbance” has no variance at the within
    level. The variable appears to be a between-level variable. Please
    remove this variable from the level 1 section in the model syntax.

**Comment by TDJorgensen** [comment]
> how can I solve the problem?

By doing what the message says:

> Please remove this variable from the level 1 section in the model syntax.

**Comment by yixiaoxia0811** [comment]
But I think disturbance is an important factor that affects forest productivity, diversity and complexity, and the level 1 already contains all the causality I want to study, the only problem not solved is the random effect (in this case, the plot). How to deal with this warning, or the warning does not affect the fitting of the model and can be ignored?

**Comment by TDJorgensen** [comment]
Are you saying that you do not expect all `disturbance` values to be identical within the same `plot`?  You think `disturbance` should vary within `plot`?

**Comment by yixiaoxia0811** [comment]
All the data are from 9 plots, and there are three types of disturbance in all my 9 plots. The disturbance values in each plot is the same, but between different plots is different.

**Comment by TDJorgensen** [comment]
> The disturbance values in each plot is the same, but between different plots is different.

Then, as the warning message told you, `disturbance` has no level-1 variance, so you need to remove it from your level-1 model.  If it only varies between plots, it can only explain between-plot variance.  It might help to review some introductory concepts in multilevel modeling:

https://statisticalhorizons.com/wp-content/uploads/MLM2-Sample-Materials-1.pdf

https://psu-psychology.github.io/psy-597-SEM/15_multilevel/multilevel_sem.html

**Comment by yixiaoxia0811** [comment]
I will learn more about multilevel modeling ,thank you very much for your help.

**Comment by yrosseel** [comment]
Not an issue, more a question for the discussion forum. Closing.
