### ISSUE TITLE
Compatibility of lavaan with tibble 3.0

### ISSUE THREAD

**Issue by lionel-** [yrosseel/lavaan#175]
tibble data frames have gotten stricter since version 3.0 (see https://www.tidyverse.org/blog/2020/04/tibble-3-0-0/ for details). Apparently this causes issues with lavaan because of this difference in behaviour:

```r
tibble::tibble(x = 1)[[NA]]
#> Error: Must extract column with a single valid subscript.
#> ✖ Subscript `NA` can't be `NA`.

data.frame(x = 1)[[NA]]
#> NULL
```

See https://github.com/r-lib/tidyselect/issues/191 for an example of this issue.

Would you consider taking inputs with `as.data.frame()`? This would guarantee your inputs fully behave like a data frame. Counting on inheritance does not guarantee this (it could be a tibble, a data.table, or an sf data frame which all behave differently).

**Comment by TDJorgensen** [comment]
The development version of lavaan already uses `as.data.frame()`: #163 
Hopefully this will cut down on future confusion for users unfamiliar with lack-of-inheritance issues in the tidyverse.

**Comment by lionel-** [comment]
Glad this is fixed.
