### ISSUE TITLE
lavPredict() does not work with factors

### ISSUE THREAD

**Issue by topherhuebel** [yrosseel/lavaan#176]
Hi Yves,
lavPredict() works if the variables are numeric, but it does not work if they are coded as factors. 

Did you find a solution for the problem?

**Comment by yrosseel** [comment]
The reason was that in the original dataset (used to fit the model), the number of categories (for some variables) was not the same as in the 'new' dataset. This will now trigger a more informative error message. Fixed in 0.6-7.
