### ISSUE TITLE
lavPredict() does not create empty NA rows if missing values in the questionnaire items

### ISSUE THREAD

**Issue by topherhuebel** [yrosseel/lavaan#177]
I am using lavaan 0.6-5
It only creates scores for individuals without NAs
when I use "append.data" it only appends the columns that I have used for the original model and not the whole new data frame with the new data -> maybe this could be an alternative option that it creates complete new data frame?

Or it creates empty rows for the individuals that have NAs on some of their questionnaire items

**Comment by yrosseel** [comment]
The reason was that the original model was not fitted with missing = "ml"
