### ISSUE TITLE
Incorrect idiom leads to unclear error message

### ISSUE THREAD

**Issue by cjvanlissa** [yrosseel/lavaan#178]
I believe this error message:
`lavaan ERROR: some latent variable names collapse with observed variable names`

should be:
`lavaan ERROR: some latent variable names collide with observed variable names`

Can't find the source in the code, otherwise I'd submit a fix, but this should be easy to address.

**Comment by yrosseel** [comment]
Good suggestion, thanks. Changed in dev lavaan 0.6-7.1564
