### ISSUE TITLE
dCOV can be NA when optimizer goes off the rails

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#179]
Hi Yves,

When checking the model-implied Sigma for negative variances [here](https://github.com/yrosseel/lavaan/blob/master/R/lav_model_objective.R#L40), it is possible that `lav_model_implied()` returned missing values in Sigma, which leads to an uninformative error:

https://groups.google.com/d/msg/lavaan/OBoW1y8QvYA/Hli7g3NvBQAJ

A solution would be to first check `if (any(is.na(dCOV)))`, but as you can see in the thread above (which has a reproducible example), it seems to happen when the optimizer goes way off the rails.  Not sure if you are interested in trying to prevent the error instead of detecting it, but it seems to happen with theta parameterization, which I recall has been elusive for you in the past.

**Comment by yrosseel** [comment]
Thanks. Good to have a reprex. I did what you suggested (catching any NA values in COV), and that seems to do the trick. Fixed in dev lavaan 0.6-7.1565
