### ISSUE TITLE
Issue with sampling.weights in version 0.6-6

### ISSUE THREAD

**Issue by rpc5108** [yrosseel/lavaan#182]
Hello Yves,

Per your instructions, I have attached the code I am using along with the data to see if there is a bug in version 0.6-6 related to the sampling.weights command. When I run this, I get the following error message:

Error in stats::cov.wt(Y, wt = wt, method = "ML") : 
  'x' must contain finite values only

Thank you for your help with this. 

Best,

Ryan
[SWB Null Model Code.txt](https://github.com/yrosseel/lavaan/files/4777515/SWB.Null.Model.Code.txt)

[MySWBdata.Rdata.zip](https://github.com/yrosseel/lavaan/files/4777518/MySWBdata.Rdata.zip)

**Comment by yrosseel** [comment]
Thanks for the reprex. This is now fixed in lavaan dev 0.6-7.1573.

**Comment by rpc5108** [comment]
Hello Yves,

Thank you for the update. I really appreciate all of the time and effort you put into lavaan. I will be sure to download the new version.

Best,

Ryan

Sent from my iPad

On Jul 18, 2020, at 2:04 PM, Yves Rosseel <notifications@github.com> wrote:

﻿

Thanks for the reprex. This is now fixed in lavaan dev 0.6-7.1573.
