### ISSUE TITLE
Bootstrap for indirect effects with robust estimators?

### ISSUE THREAD

**Issue by mkilb** [yrosseel/lavaan#190]
Hi, 

I would like to get bootstrapped CIs for my estimates (especially a total and an indirect effect in a mediation model), but I need to use a robust estimator (mlm) because of non-normality of the data.

Is there a possibility to do both at the same time? se = "bootstrap" and estimator = "mlm/mlr" does not work at the same time. I tried to first estimate the lavaan object with mlm and afterwards bootstrap SE/CIs with the bootstrapLavaan() function. It works, but I don't get the values for the total1 (total1    := c1 + (a1 * b1)) and indirect1 (indirect1 := a1 * b1), only the values for a1, b1 and c1.

Can I specify something in the function, to also bootstrap indirect1 and total1? Or is there another possibility I am missing?

Best,
Michael

**Comment by TDJorgensen** [comment]
If you provide an R script (embedded within backticks so the Markdown conversion allows it to be copied), it will be easier to see what is going wrong.  But I expect that if you are merely reproducing the help-page example (i.e., with the default `FUN="coef"`), then that is the problem.  You need to add an argument to request user-defined parameters, as described on the `class?lavaan` help page.  See the effect here:

```
set.seed(1234)
X <- rnorm(100)
M <- 0.5*X + rnorm(100)
Y <- 0.7*M + rnorm(100)
Data <- data.frame(X = X, Y = Y, M = M)
model <- ' # direct effect
             Y ~ c*X
           # mediator
             M ~ a*X
             Y ~ b*M
           # indirect effect (a*b)
             ab := a*b
           # total effect
             total := c + (a*b)
         '
fit <- sem(model, data = Data)
coef(fit) # only includes actually estimated model parameters
coef(fit, type = "user") # also includes user-defined (functions of) parameters
```

You can define your own custom function that is a wrapper around `coef()`, then pass that to `bootstrapLavaan()`, e.g.,

```
myCoef <- function(x) {
  library(lavaan)
  stopifnot(class(x) == "lavaan")
  coef(x, type = "user")
}

bs <- bootstrapLavaan(fit, ..., FUN = myCoef)
```
