### ISSUE TITLE
lavaanList(store.slots = "samplestats") doesn't save SampleStats

### ISSUE THREAD

**Issue by Suppanut** [yrosseel/lavaan#191]
https://github.com/yrosseel/lavaan/blob/46f3ff445a7334b04894afc6ac3bc57fdaf2ef6b/R/xxx_lavaanList.R#L275

Should this be something like `RES$SampleStats <- lavobject@SampleStats` ?

**Comment by yrosseel** [comment]
Indeed. Fixed now in 0.6-8.1617.
