### ISSUE TITLE
Lavaan: multiple mediators and control variable in single model

### ISSUE THREAD

**Issue by JSchaev** [yrosseel/lavaan#194]
Hi all,

I would like to fit a lavaan model with as outcome 'language decline' and the effect of 'age', and 2 mediators ('cortex1' and 'cortex2'). The model should be corrected for someone's baseline language performance (c2).

However, would it be possible to model also the effect of age on baseline language performance in the same model or should one code a different model for this?

I tried some code (see below). 

Any advice would be greatly appreciated !

library(lavaan)
contrastsMediation_full <- 
'language_decline~ b1 * cortex1 + b2 * cortex2 + c1 * Age + c2 * language_baseline
cortex1 ~ a1 * Age + a3 * language_baseline
cortex2 ~ a2 * Age + a4 * language_baseline
#indirect effects
indirect1 :=  a1 * b1
indirect2 := a2 * b2
# contrasts
contrast := indirect1 - indirect2
# total effect
total1 := c1 + (a1 * b1) + (a2 * b2)
total2 :=  c2 + (a3 * b1) + (a4 * b2)
# covariates
#M1 ~~ M2
cortex1~~ cortex2
'
fit <- sem(model = contrastsMediation_full, data = Dataset_n179, test="bootstrap")
summary(fit, standardized=T, fit.measures=T, rsq=T)

**Comment by yrosseel** [comment]
This is a modeling question (please post to SEMNET, or the lavaan discussion group). Not an lavaan issue.
