### ISSUE TITLE
"Error: Can't convert <haven_labelled> to <character>

### ISSUE THREAD

**Issue by tmeghnaa** [yrosseel/lavaan#196]
Hello,

My student and I both loaded the same dataset, installed the same packages, and were running the same code. When I run "frq" I get a frequency table and the variable is labeled as "numeric." When my student runs the same code, she gets "Error: Can't convert <haven_labelled> to character." Any thoughts on where we might be going wrong?

Thank you!

**Comment by mddavilap** [comment]
I am not sure if there is a frq command in the lavaan package. It will be more helpful if you could share your code. Also, take into consideration that the haven labelled message could be referring to the haven package in the tidyverse ecosystem.

**Comment by tmeghnaa** [comment]
I think, the frq command is part of the sjmisc. Maybe having haven and tidyverse might be causing issues?

I don't have my student's code, but we are both typing the same thing what I am using is:
install.packages("haven")
library(haven)
install.packages("lavaan")
library(lavaan)
install.packages("tidyverse")
library(tidyverse)
install.packages("sjmisc")
library(sjmisc)

dim(pr2551)
frq(pr2551$strategies_16)

In response I get a frequency table, but she gets that error message in her console. [
![R-error](https://user-images.githubusercontent.com/28224206/101383288-f14c1380-3886-11eb-9037-176237c7ca45.png)
](url)

**Comment by tmeghnaa** [comment]
Also, just to clarify, the code I wrote above is what my student was using. Because I had my packages already installed, I only ran the libraries.

**Comment by TDJorgensen** [comment]
> the frq command is part of the sjmisc

Then this is not a lavaan issue (try running the script without loading lavaan, and you should run into the same issue).  To refer this to the `sjmisc` GitHub project, you can find their URL on the `sjmisc` package's CRAN page:

https://cran.r-project.org/package=sjmisc

Look for "URL" or "BugReports".

But first, I would recommend comparing your `sessionInfo()` output to verify you are both running the same software versions.

**Comment by tmeghnaa** [comment]
Thank you so much! I will check the version. That was the only other thing that makes sense with this issue. I did however send her this simple code below:

x <- c(1:10)
frq(x)

And this worked. The frq worked, so I will check the version next. 
Thank you for helping!
