### ISSUE TITLE
Discrepancy between test = "bootstrap" p-values and confidence interval boundaries

### ISSUE THREAD

**Issue by LukasWallrich** [yrosseel/lavaan#198]
Preface: This is almost certainly not a lavaan bug, but seems to be a gap in the documentation - that's why I am posting here rather than on SO. 

I am running a simple mediation model and trying to bootstrap the confidence interval and p-value for the indirect effect. I get a p-value of .083 and a (percentile-based) CI of [.01, .17]. In principle, I would expect the two results to agree if they are both bootstrapped? How is the bootstrapped based p.value calculated? I cannot find information on that in the tutorial or the docs. Any pointers would be much appreciated.

```
med_mod <- ("
            val_div_society ~ c*soc_act + b*freq_discuss_differences
            freq_discuss_differences ~ a*soc_act
            indirect := a*b
            direct := c
            total := ind+direct
            ")

library(lavaan)
set.seed(300688)
fit <- sem(med_mod, df, se = "bootstrap", test = "bootstrap", bootstrap = 5000)
```

**Comment by yrosseel** [comment]
Good point. The p-value is still assuming that the z-statistic follows a standard normal distribution. The z-statistic is just the estimate divided by the (bootstrap-based) standard errors. I will add a small note about this in the documentation of parameterEstimates().
