### ISSUE TITLE
getting strange error with missing = "FIML"

### ISSUE THREAD

**Issue by jmobrien** [yrosseel/lavaan#206]
https://github.com/yrosseel/lavaan/blob/aa2363ab835241b0b11819bfcf741250dd6a4ef4/R/lav_mvnorm_missing_h1.R#L67-L69

I was fitting a simple single-factor model using missing = "FIML" using a dataset with many fully missing cases on the indicators (n = 101 present, n = 690 missing), and modest partial missing in the n =101 cases.  Fitting failed with the error "Error in eigen(S, symmetric = TRUE) : infinite or missing values in 'x'.  

Notably, if I removed the missing cases beforehand, the model seemed to work just fine.  

I tracked the issue down to the referenced lines.  The call to `.colMeans()` here is passed the full data matrix, including the fully missing rows.  However, the count of rows (`N`) passed to parameter `m` is only the number of rows with non-missing cases.  In this case, this produced some `NaN`'s in the resulting `Mu0`, leading to errors when this was passed to `lav_mvnorm_missing_estep` function called slightly below the referenced spot.  

I'm unclear the role played by the `m` and `n` dimension parameters for `.colMeans()`, but as it stands they don't actually match the dimensions of the `Y` matrix.   (If they do--such as if I manually remove the fully-missing cases beforehand--this issue does not occur).  Playing around with different `m`s produced different values in the elements of `Mu0`--including different parts of the vector ending up with `NaN`.  So, I'm not sure, but I'm concerned this section isn't doing what is expected for addressing missingness.

**Comment by yrosseel** [comment]
Indeed. Thanks for already finding the source of the problem: m should indeed be nrow(Y), and not 'N' where we have already removed the missing lines. I have now changed this. Could you check if this solves the problem for your dataset?

**Comment by jmobrien** [comment]
Thanks!  I can't check directly right now, as my dataset is on a server that has a process to be updating (I'll be doing that now, though!).  But yesterday I did try swapping in the nrow(Y) value manually while in the debugger, and that seemed to clear things up.  So I feel pretty confident this will work, but I'll of course follow up if something surprises me.

Thanks again!

**Comment by jmobrien** [comment]
Reprex for the issue and testing the fix:

` r 
# Basic model:
mod <-"
LV =~x1 + x2 + x3 + x4 + x5 + x6 + x7
"

# Generate some data:
mod_sim <-"
LV =~.85*x1 + .85*x2 + .85*x3 + .85*x4 + .85*x5 + .85*x6 + .85*x7
"

set.seed(123)
simdat <- 
  lavaan::simulateData(mod_sim, sample.nobs = 101) 

simdat_miss <-
  purrr:::modify(simdat, 
                 ~dplyr::case_when(
                   sample(1:20, 101, replace = TRUE) == 1 ~ NA_real_,
                   TRUE ~ .x))


# Chunks of missing data above and below
simdat_miss_emptyfew <- 
  tibble::add_row(simdat_miss, x1 = rep(NA, 5))
simdat_miss_emptyfew <- 
  tibble::add_row(simdat_miss_emptyfew, x1 = rep(NA, 5), .before = 1)


# Add in some junk row padding:
simdat_miss_emptymany <- 
  tibble::add_row(simdat_miss, x1 = rep(NA, 300))
simdat_miss_emptymany <- 
  tibble::add_row(simdat_miss_emptymany, x1 = rep(NA, 300), .before = 1)

# Make into matrix, as done internally:
simdat <- as.matrix(simdat)
simdat_miss <- as.matrix(simdat_miss)
simdat_miss_emptyfew <- as.matrix(simdat_miss_emptyfew)
simdat_miss_emptymany <- as.matrix(simdat_miss_emptymany)

# Different column mean estimation with any fully missing rows:
.colMeans(simdat_miss, 101, 7, na.rm = T)
.colMeans(simdat_miss_emptyfew, 101, 7, na.rm = T)
.colMeans(simdat_miss_emptymany, 101, 7, na.rm = T) # What I saw, with the NaNs

# But matches if they use the right row count:
.colMeans(simdat_miss, 101, 7, na.rm = T)
.colMeans(simdat_miss_emptyfew, 110, 7, na.rm = T)
.colMeans(simdat_miss_emptymany, 701, 7, na.rm = T)

# Checking fix from 0.6-9.1638:
mod <-"
LV =~x1 + x2 + x3 + x4 + x5 + x6 + x7
"

test <- 
  sem(mod, simdat_miss, missing = "fiml")
test2 <- 
  sem(mod, simdat_miss_emptyfew, missing = "fiml")
test3 <- 
  sem(mod, simdat_miss_emptymany, missing = "fiml")

# Good
identical(
broom::tidy(test),
broom::tidy(test2)
)

# Good
identical(
broom::tidy(test2),
broom::tidy(test3)
)
`

So, it looks like this is working fine.  I think this implies the adjustment also addressed some estimation issues that could have  occurred whenever `missing = "fiml"` was used with datasets with smaller numbers of fully-missing cases.  In our case that's something we encounter almost constantly, so that's good.
