### ISSUE TITLE
The est argument in standardizedSolution does not work as described in the documentation (or maybe it does?)

### ISSUE THREAD

**Issue by sfcheung** [yrosseel/lavaan#208]
(I posted to the Google group but now I think maybe it is an issue that is more suitable to be posted here.)

I want to use user-supplied parameter estimates to compute the standardized estimates of a model. Only the implied standardized solution is needed, not the standard errors. I thought I should use the argument `est` in `standardizedSolution`. From the documentation, `est` is:

"Parameter values (as in the ‘est’ column of a parameter table). If provided, they will be used instead of the parameters that can be extract from object."

However, it seems that it does no work as I expected:

This is the code (tested in lavaan 0.6-8, R 4.0.5, Windows):

```
library(lavaan)

dat_cov <- matrix(
    c(  4, 1.8,  1.6,
      1.8, 9.0,  4.8,
      1.6, 4.8, 16.0),
    3, 3,
    byrow = TRUE
  )
rownames(dat_cov) <- colnames(dat_cov) <- c("x", "y", "m")

dat_cov
n <- 100

mod <-
"
m ~ x
y ~ m + x
"

fit0 <- sem(mod, sample.cov = dat_cov, sample.nobs = n, fixed.x = FALSE)
standardizedSolution(fit0)

dat_cov1 <- dat_cov
dat_cov1[1, 1] <- dat_cov1[1, 1] <- 6
dat_cov1
fit1 <- sem(mod, sample.cov = dat_cov1, sample.nobs = n, fixed.x = FALSE)
standardizedSolution(fit1)

standardizedSolution(fit0, est = coef(fit1))
```

The results:

```
> standardizedSolution(fit1)
  lhs op rhs est.std    se      z pvalue ci.lower ci.upper
1   m  ~   x   0.163 0.097  1.678  0.093   -0.027    0.354
2   y  ~   m   0.370 0.085  4.349  0.000    0.203    0.537
3   y  ~   x   0.185 0.090  2.056  0.040    0.009    0.361
4   m ~~   m   0.973 0.032 30.619  0.000    0.911    1.036
5   y ~~   y   0.807 0.071 11.377  0.000    0.668    0.946
6   x ~~   x   1.000 0.000     NA     NA    1.000    1.000
> standardizedSolution(fit0, est = coef(fit1))
  lhs op rhs est.std    se      z pvalue ci.lower ci.upper
1   m  ~   x   0.133 0.096  1.389  0.165   -0.055    0.321
2   y  ~   m   0.370 0.085  4.330  0.000    0.202    0.537
3   y  ~   x   0.151 0.089  1.698  0.089   -0.023    0.325
4   m ~~   m   0.973 0.038 25.347  0.000    0.898    1.049
5   y ~~   y   0.807 0.072 11.138  0.000    0.665    0.949
6   x ~~   x   1.500 0.000     NA     NA    1.500    1.500
```

To achieve what I want, I need to do this:

```
fit0_from_fit1 <- fit0
fit0_from_fit1@ParTable <- as.list(parameterTable(fit1))
fit0_from_fit1@Model <- lav_model_set_parameters(fit0@Model, coef(fit1))
standardizedSolution(fit0_from_fit1)$est.std
standardizedSolution(fit1)$est.std
```

The results are then identical:

```
> standardizedSolution(fit0_from_fit1)$est.std
[1] 0.1632993 0.3698630 0.1845506 0.9733333 0.8068493 1.0000000
> standardizedSolution(fit1)$est.std
[1] 0.1632993 0.3698630 0.1845506 0.9733333 0.8068493 1.0000000
```

I need to update both the parameter table (`@ParTable` slot) and the model (`@Model`) to make `standardizedSolution` use the parameter estimates in `fit1` to find the standardized solution using `fit0` as the input lavaan object.

I tested and confirmed that updating only `Partable` or `Model` cannot produce the correct standardized solution.

Is this intended behavior of the `est` argument in `standardizedSolution`? If yes, then the documentation on this argument may need to provide more information on this argument.

**Comment by TDJorgensen** [comment]
Out of curiosity, what exactly are you trying to accomplish by using a one model's parameter estimates as the basis for standardizing the estimates from a different model?

I asked Yves to include the `est=` argument (along with `GLIST=`) so that I could capitalize on `standardizedSolution()` for `lavaan.mi` objects in `semTools`.  They are not meant for normal use, but they had to be public for me to pass that information in the `summary()` method for `lavaan.mi` objects.  My need was based on providing pooled estimates (both the `@ParTable` vector and the LISREL matrices in `@Model@GLIST`), which are not available in the `lavaanList` object that forms the basis of `lavaan.mi`.

You have to use both `est=` and `GLIST=` arguments in conjunction.  Then it shouldn't be necessary to replace the `@Model` slot (since it is the `object@Model@GLIST` information that is used) nor the `@ParTable` slot in your fitted model.

**Comment by sfcheung** [comment]
Thanks for your explanation. I checked and found that `GLIST` indeed can be used in my example to achieve the desired results (thanks for the advice):

```
standardizedSolution(fit0, est = coef(fit1), GLIST = fit1@Model@GLIST)
```

I have `fit1` in my example because I need the "answers" (standardized solution in `fit1`) to check whether `standardizedSolution` can yield the correct standardized solution *if* the parameter estimates were as in `fit1`. As in `lavaan.mi`, I am writing a function to extend `lavaan` (still in the early stage). In the actual case I need to handle, I do not even have `fit1` as in my example. I only have a vector of the values of free parameters in the model. For example:

```
new_est <- coef(fit1)
fit0_test <- fit0
fit0_test@Model <- lav_model_set_parameters(fit0@Model, new_est)
standardizedSolution(fit0_test, est = new_est)
```

`new_est` set to `coef(fit1)` just to confirm that the standardized solution of `fit1` can be reproduced. In my case, I don't have `fit1`, but only have the vector `new_est`. Therefore, I cannot use `GLIST`, unless there is another function than can create a `GLIST`  from a vector of parameter estimates

**Comment by sfcheung** [comment]
Perhaps this issue can be closed because the documentation did remark that "The est, GLIST, and partable arguments are not meant for everyday user". The documentation for `est`, "Parameter values (as in the ‘est’ column of a parameter table). If provided, they will be used instead of the parameters that can be extract from object." did describe what it does. It is me who incorrectly believed that just changing `est` is enough to yield the standardized solution based on the values supplied to `est`.

**Comment by yrosseel** [comment]
I have updated the documentation, to make clear that GLIST is also needed if the 'est' argument is used (and vice versa).
