### ISSUE TITLE
parameter table input with multigroup analysis

### ISSUE THREAD

**Issue by mcfanda** [yrosseel/lavaan#209]
Hello,
I find it very useful to use the output of lavanify() as input for lavaan() or sem(). However, this method seems to produce an error when the model involves multigroup analysis. On version 0.6-8 it invariably gives the error
 `Error in crossprod(Diff, Sigma.inv) : non-conformable arguments`.

Here is how to reproduce the issue
```
N<-100
data<-data.frame(x=rnorm(N),y=rnorm(N),gr=rbinom(N,1,.5))
syn<-"y~x"
mod1<-lavaan::lavaan(syn,data=data,group="gr",fixed.x=T,int.ov.free = T,auto.var=T)
lavaan::summary(mod1)

tab<-lavaan::lavaanify(syn,ngroups = 2,auto.var=T,fixed.x = T)
mod2<-lavaan::lavaan(tab,data=data,group="gr",fixed.x=T,auto.var=T,int.ov.free = T)
```

**Comment by TDJorgensen** [comment]
Make sure you also specify the mean structure in the parameter table that you are requesting when you fit the model:

```
tab <- lavaan::lavaanify(syn, ngroups = 2, auto.var = TRUE, fixed.x = TRUE,
                         int.ov.free = TRUE, meanstructure = TRUE)
```

**Comment by mcfanda** [comment]
great! this way it works, thanks a lot
