### ISSUE TITLE
Error in `lavTestLRT` when `method = "satorra.2000"`, `A.method = "exact"`, and the models have equality constraints

### ISSUE THREAD

**Issue by sfcheung** [yrosseel/lavaan#211]
Hi. In version 0.6-8, I found that `lavTestRT` can raise an error when the models being compared has a linear equality constraint, even if the difference between the models does not involve this constraint.

```
library(lavaan)

dat <- HolzingerSwineford1939

mod1 <-
"
x1 ~ a*x2 + a*x3
x4 ~ c*x1 + d*x2
"
fit1 <- sem(mod1, dat, test = "satorra.bentler")

mod0 <-
"
x1 ~ a*x2 + a*x3
x4 ~ c*x1 + d*x2
c == 0
"
fit0 <- sem(mod0, dat, test = "satorra.bentler")

tryCatch(lavTestLRT(fit0, fit1,
                    method = "satorra.2000",
                    A.method = "exact"), error = function(e) e)
lavTestLRT(fit0, fit1, method = "satorra.2000", A.method = "delta")
```

With `A.method = "exact"`, `lavTestLRT` raises this error:

```
<simpleError in A %*% t(m1@Model@eq.constraints.K): non-conformable arguments>
```

With `A.method = "delta"`, `lavTestLRT` runs without errors.

It seems that, with a linear equality constraint,  `lav_test_diff_A`, which is called by `lav_test_diff_Satorra2000`, the function being called by `lavTestLRT`, returns a vector with its length depending on `method` (`A.method` from `lavTestLRT`)

```
> lavaan:::lav_test_diff_A(fit1, fit0, method = "exact")
     [,1] [,2] [,3] [,4] [,5] [,6]   
[1,]    0    0    1    0    0    0   
> lavaan:::lav_test_diff_A(fit1, fit0, method = "delta")    
          [,1]      [,2]         [,3]      [,4]         [,5]
[1,] 0.1824703 0.9433742 1.109932e-09 0.2770373 6.331741e-16
```

In `lav_test_diff_Satorra2000`, if `m1` has one or more equality constraint (`m1@Model@eq.constraints` true), the output from `lav_test_diff_A` (`A`) will be expanded to a "full" parameter vector:

https://github.com/yrosseel/lavaan/blob/5ae84823b65c4f1aa34009dde018aefa07fafb8c/R/lav_test_diff.R#L58-L62

This behavior is correct if `A.method` is `"delta"` because `lav_test_diff_A` returns a reduced parameter vector. However, if `A.method` is `"exact"`, the returned parameter is already a full parameter vector. This led to the error above.

Not sure if this should be fixed (maybe "exact" should not be used in this case?). If this should be fixed, how about converting the parameter vector to a reduced one in `lav_test_diff_A` if the method is `"exact"`? E.g., after these lines:

https://github.com/yrosseel/lavaan/blob/5ae84823b65c4f1aa34009dde018aefa07fafb8c/R/lav_test_diff.R#L345-L347

Add:
```
if(m1@Model@eq.constraints) {
    A <- A %*% m1@Model@eq.constraints.K
}
```

This may look redundant because it will be converted back to a full parameter vector immediately when `lav_test_diff_Satorra2000` receives the result. However, this ensures that interface of `lav_test_diff_A` is consistent. It always returns a reduced parameter vector, whether the method is `"exact"` or `"delta"`.

However, there is another function, `ctr_pml_plrt_nested`, that also calls `lav_test_diff_A` . I have not used that function and therefore I am not sure whether this change will affect `ctr_pml_plrt_nested`.

**Comment by yrosseel** [comment]
Thanks. I fixed this in dev lavaan 0.6-9. The results will not be identical, but they should be similar enough.
