### ISSUE TITLE
three-way interaction with colons

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#220]
From the lavaan forum:

https://groups.google.com/g/lavaan/c/v-rNKllEaOY/m/rK_5QfF3BgAJ

Does the colon operator currently support only two-way interaction? I tried something like x1:x2:x3 and it does not work:

```
sigma <- matrix(.4, 4, 4)
diag(sigma) <- 1
set.seed(84324)
dat <- MASS::mvrnorm(100, rep(0, 4), sigma)
colnames(dat) <- paste0("x", 1:4)
mod <- "
x4 ~ x1 + x2 + x3 + x1:x2 + x1:x3 + x2:x3 + x1:x2:x3
"
fit <- sem(mod, dat)
parameterEstimates(fit, remove.nonfree = TRUE)
```

The output:
```
> parameterEstimates(fit, remove.nonfree = TRUE)
  lhs op   rhs    est    se      z pvalue ci.lower ci.upper
1  x4  ~    x1  0.041 0.095  0.436  0.663   -0.144    0.227
2  x4  ~    x2  0.232 0.115  2.014  0.044    0.006    0.458
3  x4  ~    x3  0.266 0.105  2.526  0.012    0.060    0.473
4  x4  ~ x1:x2 -0.054 0.084 -0.640  0.522   -0.219    0.111
5  x4  ~ x1:x3 -0.034 0.106 -0.326  0.745   -0.242    0.173
6  x4  ~ x2:x3 -0.005 0.111 -0.046  0.963   -0.222    0.212
7  x4 ~~    x4  0.737 0.104  7.071  0.000    0.533    0.941
```

**Comment by alisoufizadeh** [comment]
Hi, I'm trying a three-way interaction (moderated moderation) in lavaan and it does not work (I get the same results). 
It seems to ignore the third variable in the interaction.

**Comment by yrosseel** [comment]
I looked into this and decided that it would be too complicated (for the lavaan syntax) to support three-way (or higher-order) interaction terms. But in 0.6-12, at least there will be an error message, like this:

Error in lavParseModelString(model) : lavaan ERROR:
    Three-way or higher-order interaction terms (using multiple
    colons) are not supported in the lavaan syntax; please manually
    construct the product terms yourself in the data.frame, give them
    an appropriate name, and then you can use these interaction
    variables as any other (observed) variable in the model syntax.
    Problematic term is: x1:x2:x3
