### ISSUE TITLE
0.6.13 throws an error that 0.6.12 does not

### ISSUE THREAD

**Issue by profandyfield** [yrosseel/lavaan#261]
I have a model used in my textbook and teaching materials. Which you can reproduce as follows

```
infidelity_tib <- readr::read_csv(file = "http://www.discovr.rocks/csv/lambert_2012.csv")

infidelity_mod <- 'phys_inf ~ c*ln_porn + b*commit
                   commit ~ a*ln_porn

                   indirect_effect := a*b
                   total_effect := c + (a*b)
                   '
infidelity_fit <- lavaan::sem(infidelity_mod, data = infidelity_tib, missing = "FIML", estimator = "MLR")
summary(infidelity_fit)
```

This is my output using `lavaan 0.6.12`

```
lavaan 0.6-12 ended normally after 24 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                         7

  Number of observations                           240
  Number of missing patterns                         2

Model Test User Model:
                                              Standard      Robust
  Test Statistic                                 0.000       0.000
  Degrees of freedom                                 0           0

Parameter Estimates:

  Standard errors                             Sandwich
  Information bread                           Observed
  Observed information based on                Hessian

Regressions:
                   Estimate  Std.Err  z-value  P(>|z|)
  phys_inf ~                                          
    ln_porn    (c)    0.460    0.245    1.874    0.061
    commit     (b)   -0.270    0.071   -3.806    0.000
  commit ~                                            
    ln_porn    (a)   -0.470    0.229   -2.055    0.040

Intercepts:
                   Estimate  Std.Err  z-value  P(>|z|)
   .phys_inf          1.365    0.315    4.332    0.000
   .commit            4.203    0.053   79.603    0.000

Variances:
                   Estimate  Std.Err  z-value  P(>|z|)
   .phys_inf          0.431    0.054    7.974    0.000
   .commit            0.531    0.050   10.672    0.000

Defined Parameters:
                   Estimate  Std.Err  z-value  P(>|z|)
    indirect_effct    0.127    0.068    1.876    0.061
    total_effect      0.587    0.243    2.411    0.016
```

Some colleagues have been trying to use this model for teaching but with version `0.6.13` and they get this error from `summary(infidelity_fit)`

```
Length  Class   Mode 
     1 lavaan     S4 `
```

and this error from `broom::glance(infidelity_fit)`

```
Error in solve.default(X[[i]], ...) : 
  Lapack routine dgesv: system is exactly singular: U[3,3] = 0
Calls: sourceWithProgress ... lav_fit_fiml_corrected -> lapply -> FUN -> solve.default
Execution halted
```

This is actually stopping my `learnr` tutorial from rendering (because the model is fitted as part of the rendering process) so it would be super useful to know what's changed between the versions of `lavaan` and what (if anything) we can do.

**Comment by yrosseel** [comment]
This is the result of a new bug that was introduced in 0.6-13. It only happens when you have missing = "ml", a robust test statistic, a model with exogenous covariates, fixed.x = TRUE (=the default), and you request fit measures.

The bug was the result of new code that implements a 'robust' RMSEA/CFI statistic in the presence of missing values.

The quick fix is to add the fixed.x = FALSE argument. Or you can downgrade to 0.6-12, or install the github version (where this is fixed).

An update (0.6-14) which includes this fix will go to CRAN soon. In a matter of days (I  hope).

**Comment by profandyfield** [comment]
Thanks for the fast response. This response is really helpful. The teaching classes that use this particular tutorial aren't for a few weeks, so we can wait for 0.6-14, but nice to know the dev release will work if need be.
