### ISSUE TITLE
lavTestLRT() does not test (or perhaps report) models in specified order

### ISSUE THREAD

**Issue by jsakaluk** [yrosseel/lavaan#263]
As described, lavTestLRT() returns "An object of class anova. When given a single argument, it simply returns the test statistic of this model. **When given a sequence of objects, this function tests the models against one another** ***in the order specified.***"

As pointed out by Christian Arnold in [a thread on the lavaan group](https://groups.google.com/g/lavaan/c/EsVJL7KX7xU/m/CSCgQpmVDgAJ), it seems that the function [explicitly and consistently]( https://github.com/cran/lavaan/blob/master/R/lav_test_LRT.R) orders models according to their df (line's 76-80) .

One solution would be an editorial fix to documentation. Even if the testing, per se, is in the specified order, the way models are consistently reported based on df conveys that the function is indifferent to the order of specification). Alternatively,  some optionality could be added to lavTestLRT(). E.g., an "order" argument that, if requested, could  reverse the testing sequence (code from Christian, below) :

`res[order(-res$Df),]`

**Comment by yrosseel** [comment]
Thanks. I updated the man page (for now). I hesitate to allow for arbitrary orderings. One can always specify just two models to be compared.
