### ISSUE TITLE
Error of `unexpected symbol` when using `efa()`

### ISSUE THREAD

**Issue by psychelzh** [yrosseel/lavaan#264]
This occurs when some of the data variables are not syntactical, here is a simple reprex:

``` r
library(lavaan)
#> This is lavaan 0.6-14
#> lavaan is FREE software! Please report any bugs.
data <- tibble::tibble(
  `1BACK` = rnorm(100),
  `2BACK` = rnorm(100),
  `3BACK` = rnorm(100)
)
efa(data)
#> Error in str2lang(x): <text>:1:4: unexpected symbol
#> 1: ~ 1BACK
#>        ^
```

<sup>Created on 2023-02-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by psychelzh** [comment]
A very straight-forward way to workaround this is to add backticks (``"`"``) to all the data variables.

**Comment by yrosseel** [comment]
Indeed. This is an 'R' thing: variable names cannot start with a digit (without using backticks).

**Comment by psychelzh** [comment]
Just to make it clear. Will the backticks be added automatically by lavaan or manually by users? If the latter, I do think some documentation needs to be added to inform users.
