### ISSUE TITLE
LGM: Estimating effect on slope for specific variable at post measurement

### ISSUE THREAD

**Issue by sophieschneemelcher** [yrosseel/lavaan#268]
Hello, 

I´m using the lavaan package to estimate a latent growth model to analyse data of an intervention study with three measurement time points. The following model includes the covariates group (intervention vs. control group), gender and age. 

```
model = '
  i =~ 1*t1_hrw + 1*t2_hrw + 1*t3_hrw 
  s =~ 0*t1_hrw + 7*t2_hrw + 9*t3_hrw 
  t1_hrw ~~ a*t1_hrw                      
  t2_hrw ~~ a*t2_hrw                      
  t3_hrw ~~ a*t3_hrw                     
  i ~ group + gender + age
  s ~ group + gender + age
'
```
I have two questions based on my model:

1. Additionally I want to examine the effect on the slope specifically for my group covariate (intervention vs. control group) at post-measurement t2. To what extent would the code be specified to achieve this intent?

2. Tutorials reccomend to set the residual variances equal to each other (as I did in my code). Would you reccomend to do this aswell and if so, why?

Any support is well appreciated
Sophie

**Comment by TDJorgensen** [comment]
This isn't an issue with the software (e.g., a bug report or feature request), but a question about how to use it.  This is more appropriate for the [lavaan forum](https://groups.google.com/d/forum/lavaan) or [StackExchange](https://stats.stackexchange.com/).

**Comment by sophieschneemelcher** [comment]
Dear Terrence, 

thank you very much for your answer. I have asked my questions there so this post can be deleted.

Sophie
