### ISSUE TITLE
Reporting the requested "prepackaged option", e.g. "MLR", "MLM", in the printout of summary?

### ISSUE THREAD

**Issue by sfcheung** [yrosseel/lavaan#285]
This feature came to my mind when reading this thread:

https://groups.google.com/g/lavaan/c/DzJQVKnyJYU/m/YyuQwBpAAAAJ

Questions similar to this one was asked every once in a while in the group. When users set the `estimator` argument, they actually specify a set of "prepackaged options" (Savalei & ROsseel, 2022, p. 171). Some sets were summarized in Table 10:

Savalei, V., & Rosseel, Y. (2022). Computational options for standard errors and test statistics with incomplete normal and nonnormal data in SEM. *Structural Equation Modeling: A Multidisciplinary Journal, 29*(2), 163–181. https://doi.org/10.1080/10705511.2021.1877548

However, in the printout of summary, the entry "estimator" may not correspond to the name for the set of prepackaged options. For example, option sets like "MLM", "MLR", "WLSMV" never appear in the printout (as far as I know).

https://groups.google.com/g/lavaan/c/6oLwoboi-vQ/m/IQLAXChPAwAJ

This can be confusing to some users. First, they may not know what happened. Second, they may not know exactly what a name like "MLM", "MLR", or "WLSMV" does.

I am working on a cheat sheet or something like that, a more comprehensive version of Table 10 in Savalei and Rossel (2022). (Anyone can generate one themselves using this gist: https://gist.github.com/sfcheung/baa5e43c32d4763b859f5338a1738d79). Nevertheless, it may be beneficial for users if a row is added in the summary, to indicate the selected prepackaged options. E.g.,

```r
summary(fit)
lavaan 0.6.15 ended normally after 100 iterations

  Estimator Options Requested                      MLR
  Estimator For Parameters                          ML
  Optimization method                           NLMINB
  Number of model parameters                        26
  Number of equality constraints                     2

  Number of observations                           123
```

Although users know what they ask for when setting the argument `"estimator"`, adding a line like the one above has these advantages:

1) It lets users know that `lavaan()` does know what they set.
2) It lets users know that values like `"MLR"` does not mean an estimation method like "`MLR`" is used to estimate the parameters. Yes, this may be confusing. But this confusion will lead to questions, and then users will learn about the differences. This is good for learning how `lavaan` works.
3) It also makes it easier fro users to learn how options like `"MLR"` and `"MLM"` are different from each other, when they also examine other rows such as `Standard errors` and `Information bread`.

My two cents.

**Comment by sfcheung** [comment]
I drafted some minor changes to `summary()` and `print.lavaan.summary()` in [this commit](
https://github.com/yrosseel/lavaan/commit/ab9a1b4af6bc51298b3ab744ab10466a58ef0fc0) to implement my suggestion.

This is an illustration:

```r
# From the help of cfa()
HS.model <- ' visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '

fit <- cfa(HS.model, data = HolzingerSwineford1939)
summary(fit, estimates = FALSE)
#> lavaan 0.6.16.1868 ended normally after 35 iterations
#> 
#>   Estimator Options Set Requested              DEFAULT
#>   Estimator                                         ML
#>   Optimization method                           NLMINB
#>   Number of model parameters                        21
#> 
#>   Number of observations                           301
#> 
#> Model Test User Model:
#>                                                       
#>   Test statistic                                85.306
#>   Degrees of freedom                                24
#>   P-value (Chi-square)                           0.000

fit2 <- cfa(HS.model, data = HolzingerSwineford1939,
            estimator = "WLSMV")
summary(fit2, estimates = FALSE)
#> lavaan 0.6.16.1868 ended normally after 44 iterations
#> 
#>   Estimator Options Set Requested                WLSMV
#>   Estimator                                       DWLS
#>   Optimization method                           NLMINB
#>   Number of model parameters                        21
#> 
#>   Number of observations                           301
#> 
#> Model Test User Model:
#>                                               Standard      Scaled
#>   Test Statistic                                43.902      79.342
#>   Degrees of freedom                                24          24
#>   P-value (Chi-square)                           0.008       0.000
#>   Scaling correction factor                                  0.598
#>   Shift parameter                                            5.867
#>     simple second-order correction

fit3 <- cfa(HS.model, data = HolzingerSwineford1939,
            estimator = "MLR")
summary(fit3, estimates = FALSE)
#> lavaan 0.6.16.1868 ended normally after 35 iterations
#> 
#>   Estimator Options Set Requested                  MLR
#>   Estimator                                         ML
#>   Optimization method                           NLMINB
#>   Number of model parameters                        21
#> 
#>   Number of observations                           301
#> 
#> Model Test User Model:
#>                                               Standard      Scaled
#>   Test Statistic                                85.306      87.132
#>   Degrees of freedom                                24          24
#>   P-value (Chi-square)                           0.000       0.000
#>   Scaling correction factor                                  0.979
#>     Yuan-Bentler correction (Mplus variant)
```

@yrosseel , if you think this change is OK, I will create a PR. I don't like the name `Estimator Options Set Requested` but I do not have a better option. If you have any suggestion on the name, let me know.

I only changed a few lines. Therefore, if you would like to do it differently, free feel to copy the changes to your branch and adapt it in any ways you like. If you don't want to do it, feel free to close this issue.

**Comment by sfcheung** [comment]
Oh ... I made a careless (though harmless) mistakes. I am working inside `lavaan` and there is no need to use `lavaan::lavInspect()`. I fixed this here: https://github.com/yrosseel/lavaan/commit/7207aad03b6fda48325147ff07c0bc6eef24de53

**Comment by yrosseel** [comment]
Hm. I am not sure about this.

All the MLR/MLM/WLSMV stuff is a legacy from Mplus. I never use them myself. It is really unfortunate that the term 'estimator' (which should only be used for point estimation) is now overloaded. But the SEM literature is full of these acronyms, and that is why they are supported in lavaan. But in the long run, we should get rid of them. They do not even accurately reflect (anymore) what they are doing (eg WLSMV is in fact DWLS, with a scaled-shifted test, not a mean-and-variance-adjusted test).

My personal opinion (for now, I am still open to further arguments) is that this is mostly a documentation issue. If we would have a nice user manual, this could all be well explained. (I am trying to get this going, but I am still stuck at the funding part). 

If we really must implement something like this, I would be more inclined to add a small additional note just below the 'lavaan 0.6.16.xxxx ended normally ...' line saying, for example, that the option estimator = "MLR" has been expanded to estimator = "ML", se = "robust.huber.white", test = "yuan.bentler.mplus" (or whatever the values are of @Options$se and @Options$test).
