### ISSUE TITLE
lavaan WARNING: 2 bootstrap runs failed or did not converge.

### ISSUE THREAD

**Issue by unbri** [yrosseel/lavaan#289]
Dear community,
        When I'm using the function, se="bootstrap",there are something wrong as following, I want to know does it will affect the result. Besides, when the warmings happened, the pval of the Defined Parameters turn to null, how can I get the pval?
        Thanks a lot.

Warning message:
In lav_model_nvcov_bootstrap(lavmodel = lavmodel, lavsamplestats = lavsamplestats,  :
  lavaan WARNING: 2 bootstrap runs failed or did not converge.

**Comment by yrosseel** [comment]
The warning is just informative. If you have many (>1000) bootstrap runs, it is not a problem that 2 of them did not converge. The NA values for defined values were due to a bug in 0.6-15, but this was fixed in 0.6-16.
