### ISSUE TITLE
Starting values sanity check

### ISSUE THREAD

**Issue by philchalmers** [yrosseel/lavaan#30]
Hi Yves,

A colleague of mine was playing around with adjusting the starting values in `lavaan` and noticed a bug relating to starting values when defining residual correlations. 

This occurs when covariance terms are defined as fixed parameters, while the starting values for the variance terms ignore this information and instead are defined too low (causing a non-PD Sigma matrix). They noticed that EQS doesn't seem to do this since it appears to adjust the variance starting values accordingly until the matrices are valid. 

Here is some reproducible code demonstrating the problem. 

    C <- scan(nlines = 5)
    0.52781600 0.25541680 0.37734312 0.3666932 0.05954574
    0.25541680 0.48958089 0.29120484 0.3257644 0.07582144
    0.37734312 0.29120484 0.78670514 0.5020104 0.08264549
    0.36669320 0.32576439 0.50201044 0.7148545 0.10810947
    0.05954574 0.07582144 0.08264549 0.1081095 0.24767669
    
    C <- matrix(C,5,5)
    colnames(C) <- rownames(C) <- c("Satis","Influenc", "Climate", "Respect", "sex1f2m")
    
    model <- "
    Satis~Influenc + Climate + Respect 
    Influenc~sex1f2m
    Climate~sex1f2m
    Respect~sex1f2m
    
    #Covariances
    Influenc~~ Climate 
    Influenc ~~ Respect
    Climate~~ Respect
    "
    
    fit <- sem(model, sample.cov = C, sample.nobs = 200)
    summary(fit)
    
    #use new starting values
    model2 <- " 
    Satis~Influenc + Climate + Respect 
    Influenc~sex1f2m
    Climate~sex1f2m
    Respect~sex1f2m
    
    #Variances and Covariances
    Influenc~~ .265*Climate 
    Influenc ~~ .291*Respect
    Climate~~ .464*Respect
    "
    
    #error, variance starting value problem
    fit2 <- sem(model2, sample.cov = C, sample.nobs = 200) 
    
    sv <- sem(model2, sample.cov = C, sample.nobs = 200, do.fit=FALSE)
    cov2cor(sv@Fit@Sigma.hat[[1]]) #illegal correlations
    
    #fix the issue by changing the starting variance terms
    model3 <- " 
    Satis~Influenc + Climate + Respect 
    Influenc~sex1f2m
    Climate~sex1f2m
    Respect~sex1f2m
    
    #Variances and Covariances (suitable starting values)
    Climate ~~ start(1)*Climate
    Respect ~~ start(1)*Respect
    
    Influenc~~ .265*Climate 
    Influenc ~~ .291*Respect
    Climate~~ .464*Respect
    "
    
    fit3 <- sem(model3, sample.cov = C, sample.nobs = 200)
    summary(fit3)

I think the fix should be easy enough by simply checking whether the matrices are PD, and adjusting the free parameters accordingly until the matrices are valid. Cheers.

**Comment by yrosseel** [comment]
Finally fixed in dev 0.5-21; a check is done for non-zero (user-specified) covariances; if the corresponding variances are too small, they are set to 110% of the covariance value.
