### ISSUE TITLE
Document ":=" operator in the "model.syntax" topic

### ISSUE THREAD

**Issue by tzoltak** [yrosseel/lavaan#300]
Operator ":=" is a part of the _lavaan_ model syntax but it isn't documented in the "model.syntax" documentation topic, where all the other operators, as well as _modifiers_, are described. (In fact the only place I found information about ":=" is _lavaan's_ webpage tutorial in the topic regarding mediation.)
I think that it will be good to add description of this operator in this documentation topic.

**Comment by TDJorgensen** [comment]
The operators for (in)equality constraints are also not listed.  I'll work on a quick PR.
