### ISSUE TITLE
Model measures - lavaan 

### ISSUE THREAD

**Issue by PriscilaPCarlos** [yrosseel/lavaan#311]
Hey,

I'm working on Structural Equation Modeling using the Lavaan package, and the fit measures for my model are SRMR 0.00, RMSEA 0.00, and CFI 1.00. I've tried to find similar results in the literature, but without success. I'm struggling to reach a conclusion on whether these results invalidate my model or suggest that it's the best fit for the available data. I have a small database. 

Could I get some help, please?

> print(fitmeasures(fit.ap.fc1, c("srmr", "rmsea", "cfi", "bic", "aic")))
   srmr   rmsea     cfi     bic     aic 
  0.000   0.000   1.000 593.698 576.200 
> modindices(fit.ap.fc1, sort = TRUE, maximum.number = 10)
[1] lhs      op       rhs      mi       epc      sepc.lv  sepc.all sepc.nox
<0 linhas> (ou row.names de comprimento 0)

**Comment by TDJorgensen** [comment]
I'm guessing your model is saturated (i.e., has _df_ = 0), which means there is no way for misfit to occur.  But this topic is more appropriate to post on lavaan's Google group.  

https://lavaan.ugent.be/about/support.html

An issue on the GitHub project is a place to report bugs or request new features.

**Comment by PriscilaPCarlos** [comment]
I didn't know about the group, I will write there.
Thank you.

**Comment by TDJorgensen** [comment]
Make sure to include your syntax and `summary()` output, so there is enough information.
