### ISSUE TITLE
Bias Corrected Bootstrap

### ISSUE THREAD

**Issue by iancero** [yrosseel/lavaan#34]
Is there any way to get bias corrected bootstrap estimates for model parameters? At least for tests of indirect effects, I think these are supposed to be superior to naive bootstrap approaches. Are there plans to include different bootstrap methods (especially bias corrected and accelerated) in future releases?

**Comment by yrosseel** [comment]
See the 'boot.ci.type' argument of the parameterEstimates() function; one of the options is 'bca.simple', which corrects for bias, but not for acceleration. This was mainly to mimic Mplus. I have currently no plans to add more options, but patches are welcome.

**Comment by iancero** [comment]
Thank you so much! I'll try that right away!
