### ISSUE TITLE
unused argument (std.nox = std.nox)

### ISSUE THREAD

**Issue by cjvanlissa** [yrosseel/lavaan#359]
Dear Yves,

since the recent lavaan update, people are experiencing the following error when calling `summary()` on a lavaan object with syntax generated by `tidySEM`:

```
Error in lav_object_summary(object = object, header = header, fit.measures = fit.measures,  : 
  unused argument (std.nox = std.nox)
```

Since I am not modifying the call to summary, I'm wondering if you have an idea where this comes from?

**Comment by TDJorgensen** [comment]
Hi Caspar,

This inconsistently occurred (or didn't) after making [this change](https://github.com/yrosseel/lavaan/pull/326), and not just with your package.  Without it being reproducible, we hoped it would not become an actual problem---sorry for the inconvenience.  There seemed to be some mysterious behavior where R remembered the old `summary()` method even after the newer lavaan was installed.  This occurred until updating the blavaan package after [this PR](https://github.com/ecmerkle/blavaan/pull/75), where you can see some discussion about the weirdness that occurred.  

So if you(r users) have blavaan installed (maybe it was loaded when the error occurred?), a solution could be to uninstall blavaan, then installing [the new version](https://cran.r-project.org/web/packages/blavaan/index.html) that just went to CRAN.  It is possible that some other package besides blavaan could cause the same mysterious problem, but we could not locate any of lavaan's reverse-dependencies that explicitly use the `std.nox=` argument, so hopefully updating blavaan is the solution.  Please keep us updated, and link to this issue when anyone posts about this.

Thanks,
Terrence
