### ISSUE TITLE
Getting specific values from cfa fit

### ISSUE THREAD

**Issue by zacharynevin** [yrosseel/lavaan#36]
Hello,

How do I get specific values from a cfa fit. For example,

````
fit <- cfa.run(dataframe, cfa_structure)
summary(fit)
````
What I want to do, for example, is return values like the p-value.

**Comment by philchalmers** [comment]
This isn't an coding issue or bug, it's a general how-to question. These are better reserved for places like stackoverflow.com or the associated lavaan google-forum (https://groups.google.com/forum/#!forum/lavaan). Please close this issue, and ask your questions there. Cheers.
