### ISSUE TITLE
 Value(s) of option ncpus out of range (1 <= x <= 0)!

### ISSUE THREAD

**Issue by HugoGit39** [yrosseel/lavaan#374]
Since this week I get this error:

```
Error: lavaan->lav_options_check():  
   Value(s) of option ncpus out of range (1 <= x <= 0)!
```

using:

```
fit <- cfa(model, data = df, std.lv=T)
```

Its on a Digital Ocean droplet sith Rstudio installed on it.

Worked always well. Ncpus = 1.

tbh I dont even know how to read 1 <= x <= 0........so the number of cpus can be max 1? 

My code still runs  well on my home station.

**Comment by TDJorgensen** [comment]
This does not sound like a lavaan problem.  My guess is that it has something to do with how your virtual machine is set up.

> I dont even know how to read 1 <= x <= 0

Neither do I.  The message implies that 1 is less than 0, and x could take non-integer values.  There is an `ncpus=` argument that is only used for bootstrapping in parallel (see `?lavOptions`), but that does not look like what you are trying to do in your `cfa()` call.  

For a [reprex](https://stackoverflow.com/help/minimal-reproducible-example) to be informative, you should provide your `sessionInfo()` output along with enough syntax and data for the issue to be reproducible.  But it might not be reproducible outside of your Digital Ocean environment.  I recommend contacting their customer service for help.

**Comment by HugoGit39** [comment]
Thx for yuor quick answer :)

I know about a repex but my code is so long. Lemme check if I can make a shorter one, yet it doesnt make it clearer I uess cause it does work on my workstation.

But so somehow lavaan cant regonize the number of cpu's though when I check ncpu sin Rstudio it does say 1

So I wonder: where in the code of lavaan does it check the ncpus?

**Comment by ecmerkle** [comment]
I think the error is coming from [here.](https://github.com/yrosseel/lavaan/blob/d6f7256f299bd700ef4e5f994e2c928bd579c88a/R/lav_options_default.R#L409) 

Is it correct that, if you run `parallel::detectCores()` on your system, it returns a value of 1? If so, based on how that code is written, the smallest possible value of `ncpus` is then set to 1 while the largest value is set to 0. Hence the `1 <= x <= 0` error. This should be easy to fix...

**Comment by HugoGit39** [comment]
Yep` parallel::detectCores()` returns 1

**Comment by ecmerkle** [comment]
I just submitted a pull request to fix this. If you have an urgent need for the fix, you could try installing my fork of lavaan at https://github.com/ecmerkle/lavaan

**Comment by HugoGit39** [comment]
Thx! When will it be updated app in the cran package?

**Comment by ecmerkle** [comment]
I don't know when it will go to CRAN, but it will not be immediate (probably weeks or months). The most recent version of lavaan (0.6-18) went to CRAN on June 7, and it contained some changes to the defaults and checks. I am guessing your system had a recent upgrade to 0.6-18, which triggered the error.

**Comment by TDJorgensen** [comment]
Thanks Ed!

**Comment by HugoGit39** [comment]
Just pulled your repo @ecmerkle  and worked!

**Comment by yrosseel** [comment]
Merged now.
