### ISSUE TITLE
Incorrect class for theta matrix

### ISSUE THREAD

**Issue by mronkko** [yrosseel/lavaan#38]
The theta matrix from inspect has class "lavaan.vector", but class "lavaan.matrix.symmetric" would make more sense. Here is a test case:

´´´´
library(lavaan)

model <- '
   # latent variable definitions
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + y2 + y3 + y4
     dem65 =~ y5 + y6 + y7 + y8
   # regressions
     dem60 ~ ind60
     dem65 ~ ind60 + dem60
   # residual covariances
     y1 ~~ y5
     y2 ~~ y4 + y6
     y3 ~~ y7
     y4 ~~ y8
     y6 ~~ y8
'
fit <- sem(model, data=PoliticalDemocracy)
class(inspect(fit, "theta"))
´´´´

**Comment by yrosseel** [comment]
fixed in dev 0.5-19.892
