### ISSUE TITLE
Fixing Variance Ordinal Data

### ISSUE THREAD

**Issue by karchjd** [yrosseel/lavaan#385]
Should this not return a warning that the fixing of x8 variance is ignored because its declared ordered?

```
library(lavaan)
data <- HolzingerSwineford1939
data$x8 <- ifelse(data$x8 > mean(data$x8), 0, 1)
HS.model <- ' visual  =~ x1 + x2 + x3 
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9
              x8 ~~ 2*x8'

fit <- cfa(HS.model, data = data, ordered = "x8")
```

**Comment by yrosseel** [comment]
Indeed, this is now silently ignored. A warning would be nice, if we use `parameterization = "delta"` (the default). I will leave this issue open until this is done. (It may take a while).

**Comment by yrosseel** [comment]
Ok. I have added warning (in the github version). It looks like this:

`
Warning message:
lavaan->lavParTable():  
   variances of ordered variables are ignored when parameterization = 
   "delta"; please remove them from the model syntax; variables involved are: 
   x8
`
