### ISSUE TITLE
Enhancement: Support for unicode variable name

### ISSUE THREAD

**Issue by shun2wang** [yrosseel/lavaan#387]
Thank you for developing such a wonderful package!

This may not be a very common request, but we do have issues with some other language text variables.The following grammar cannot be parsed because it contains non-Latin letters.
I can imagine most of the time people can solve this by recoding the variable names, I am asking this question here to discuss if there is a way to enhance it and your design intention.

```r
library(lavaan)

model <- '
    因子 =~ 变量1 + x2 + x3

'
fit <- sem(model, data = PoliticalDemocracy)
summary(fit)
```

Thanks a lot.♥

cc @juliuspfadt

**Comment by yrosseel** [comment]
In the github version of lavaan, the "new" parser should now also support unicode variables. Can you give it a try and report back?

**Comment by yrosseel** [comment]
Ok. I will close the issue (for now).
