### ISSUE TITLE
Calculating score value and epc

### ISSUE THREAD

**Issue by hsdoadventure** [yrosseel/lavaan#401]
Dear Author,

I have a question regarding the Score value calculated by the function modindices(). From the code, it appears that the score value is derived from lavTech(FIT, "gradient.logl").

In the code of modinidces(), I noticed the following line:

if (object@Model@estimator %in% ("ML")) {
    score <- -1 * score # due to gradient.logl
}

It seems that the sign of the score is inverted only when the estimator is "ML" (Maximum Likelihood). For other estimators, such as least squares, the score sign does not appear to be inverted. Could this lead to an outcome where the printed score has the opposite sign? 
(I couldn’t see the code for "lavTech", but the EPC values printed by modindices() always appeared to have the correct absolute values but seem to be in the opposite direction when compared to the model modified according to the MI values. Also, the  values were the same in magnitude but had opposite signs compared to those in Mplus.)

I would appreciate your clarification.

Thank you!

**Comment by yrosseel** [comment]
Indeed. That is a temporary setback. See [this related issue](https://github.com/yrosseel/lavaan/issues/387).
In short, in 0.6-19, use the `parser = "old"` option, or install the github version (0.6-20) of lavaan.

**Comment by yrosseel** [comment]
You are right. This was my answer to a different issue (403). Please ignore. As for your question: I first needs to investigate this, as I have not looked at this code for at least 10 years. I will get back to you soon.

**Comment by hsdoadventure** [comment]
Thanks for your comment!

**Comment by yrosseel** [comment]
Ok. The EPC values indeed have the wrong (opposite) sign when the estimator is not from the ML family. Most likely, the behaviour of `lavTech(FIT, "gradient.logl")` changed at some point, and the code in modindices() was never adapted. This is now fixed in the github version.

Thanks for reporting this!
