### ISSUE TITLE
sem() now do not work for data with Japanese variable names

### ISSUE THREAD

**Issue by stanimura** [yrosseel/lavaan#403]
Previously workable data with Japanese variable name now do not work with lavaan 0.6.19.

Due to language issue,  I am unable to provide an English minimum workable example or an English error message. 
Here is output of traceback()
```
> traceback()
9: strrep(" ", pflen)
8: ldw_parse_step1(modelsrc, types)
7: ldw_parse_model_string(model.syntax = model.syntax, as.data.frame. = as.data.frame.)
6: lavParseModelString(model, parser = "new")
5: lav_lavaan_step01_ovnames_initflat(slotParTable = slotParTable, 
       model = model, dotdotdot.parser = dotdotdot$parser)
4: lavaan::lavaan(m1, data = dat, model.type = "sem")
3: eval(sc, parent.frame())
2: eval(sc, parent.frame())
1: sem(m1, data = dat)
```
The translation from Japanese error message is "strrep(" ", pflen) has error: value of 'times' is invalid."

When variable names are changed to English name, it works without problems.

**Comment by yrosseel** [comment]
Indeed. That is a temporary setback. See [this related issue](https://github.com/yrosseel/lavaan/issues/387).
In short, in 0.6-19, use the `parser = "old"` option, or install the github version (0.6-20) of lavaan.
