### ISSUE TITLE
Better error message for empirically under identified model

### ISSUE THREAD

**Issue by mronkko** [yrosseel/lavaan#43]
I am estimating the following empirically under identified model

```
library(lavaan)

d <- diag(3)
colnames(d) <- rownames(d) <- c("y1","y2","y3")
cfa("F =~ y1 + y2 + y3", sample.cov = d, sample.nobs = 100)´´´
```

I know that this should not work, but the error message that I get is not particularly informative

```
Error in solve.default(S) : 
  Lapack routine dgesv: system is exactly singular: U[1,1] = 0
```

**Comment by yrosseel** [comment]
It turns out this error was produced while computing starting values for the factor loadings.  The fabin.uni() function could not handle a singular matrix. This has now been fixed in dev 0.5-21.
