### ISSUE TITLE
DWLS with user-specified weight matrix generates an error

### ISSUE THREAD

**Issue by daob** [yrosseel/lavaan#45]
WLS.VD is NULL when WLS.V is user-specified in the lavaan call. This generates a bug in lavaan.survey when DWLS is chosen as an estimator.

Minimal R example: 

http://pastebin.com/ze2A8W7M

**Comment by yrosseel** [comment]
Confirmed. Will fix this ASAP.

**Comment by yrosseel** [comment]
Fixed now in dev 0.5-21.
