### ISSUE TITLE
[MINOR-Help files] measurementInvariance quiet argument boolean is wrong

### ISSUE THREAD

**Issue by avsfan733** [yrosseel/lavaan#48]
In the help file for the measurementInvariance function, I believe that the help file has the boolean action of the quiet argument reversed compared to actual behavior. Suggest changing 'if TRUE' to 'if FALSE' or rewriting the help file explanation to explain both states. The argument itself behaves as one would expect.

The help file reads as follows: 
>quiet	
>If TRUE, a summary is printed out containing an overview of the different models that are fitted, together with some model comparison tests.

quiet=TRUE would logically not produce output, which it does. quiet=FALSE (the default) would logically produce output, which it does. See below...

> > measurementInvariance(MODEL.invar, data=DATA_gender, group="Gender", quiet=TRUE)
>> measurementInvariance(MODEL.invar, data=DATA_gender, group="Gender", quiet=FALSE)
>
>Measurement invariance models:
>
>Model 1 : fit.configural
>Model 2 : fit.loadings
>Model 3 : fit.intercepts
>Model 4 : fit.means
>....

**Comment by avsfan733** [comment]
suggested new help verbage:

quiet	
>If TRUE, function is silenced and does not print output to console. If FALSE (default), a summary is printed out containing an overview of the different models that are fitted, together with some model comparison tests.

**Comment by psunthud** [comment]
This function is currently in the semTools package. I have opened the new issue in the semTools and I will check it out.

https://github.com/simsem/semTools/issues/15
