### ISSUE TITLE
lavTables(..., dimension = 1L) returns 100% instead of 0%

### ISSUE THREAD

**Issue by t129j179** [yrosseel/lavaan#50]
I may have found a bug in lavTables().  When I provide data where one of the groups does not have observations in both categories, it returns 100% for both categories instead of 100% for one and 0% for the other.  Maybe a situation for drop = FALSE when one dimension collapses down to length == 1?  Here is an example with binary data
`(temp <- data.frame(g = c(1,1,2,2), x = c(1,2,2,2)))`
`lavTables(temp, dimension = 1L, categorical = "x", group = "g")`
When there are more categories, it spits out an error about differing number of rows.
`(temp <- data.frame(g = c(1,1,1,2,2,2), x = c(1,2,2,1,2,3)))`
`lavTables(temp, dimension = 1L, categorical = "x", group = "g")`

**Comment by yrosseel** [comment]
Fixed now in dev 0.5-21.
