### ISSUE TITLE
PRNG seed for bootstrapLavaan

### ISSUE THREAD

**Issue by t129j179** [yrosseel/lavaan#52]
In the interest of reproducibility, could you add an argument `iseed` to the `bootstrapLavaan()` and `bootstrapLRT()` functions, which could then be passed to `parallel::clusterSetRNGStream(cl, iseed)` when you call it on line 351 of lav_bootstrap.R and on line 299 of lav_bootstrap_lrt.R?  If so, your help page description of the argument `iseed` might also warn the interested user to first set `RNGkind()[1L] == "L'Ecuyer-CMRG"`.

Thanks!

Terry

**Comment by yrosseel** [comment]
Done in dev 0.5-21.
