### ISSUE TITLE
adding unit tests

### ISSUE THREAD

**Issue by machow** [yrosseel/lavaan#56]
I've been using lavaan fairly heavily for the past year, and have been interested in getting to know the code base better. One way that would help me get a sense for how everything is set up would be to work on unit tests.

Do you have ideas on how you might want unit tests implemented for lavaan? I'm familiar with testwhat, and have used it on travis, so they should be quick to set up. A small list of functions (or a group of functions) that would be simplest / most useful to start testing may be a good way to get things rolling.

I think model syntax (e.g. lavaanify, etc..) might be a good place to start. What do you think?

**Comment by yrosseel** [comment]
lavaan could certainly use more unit tests. I have a few locally, but not enough. Model syntax would indeed be a good place to start. The lav_matrix_* functions would be another. Please contact me privately to coordinate this.

**Comment by richelbilderbeek** [comment]
Hi @yrosseel, I agree with @machow that unit tests are important in signalling the quality of code. As I consider working with an R SEM package, my first searches brought me to lavaan and [OpenMx](https://github.com/OpenMx/OpenMx). As OpenMx does have unit tests, I am likelier to use that one, as it will be a easier to communicate with the developer.

I do volunteer to add some simple unit tests, as well as Continuous Integration (i.e. using GitHub Actions).

Of course, you are maintainer/boss, so you are uninterested, it is completely fine :-)
