### ISSUE TITLE
inspect(fit, 'est') and variants returns flattened list for multigroup analyses

### ISSUE THREAD

**Issue by machow** [yrosseel/lavaan#60]
In multi-group CFA, calls like `inspect(fit, "cov.lv")` return a list with one entry per group. However,  `inspect(fit, 'est')` flattens the list, so that the 5 entries (lambda, theta, psi, nu, alpha) are repeated for each group. For example, with two groups, it will return a list with 10 entries, rather than 2.

The expected outcome seems like having one entry per subject, like 'cov.lv'.

example from lavaan docs:

```
HS.model <- '  visual =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
speed   =~ x7 + x8 + x9 '
fit <- cfa(HS.model, 
           data = HolzingerSwineford1939, 
           group = "school")

inspect(fit, 'est')     # 10 entries in single list
```

This is the case with all the what options listed under "Model Entries" in the docs:

```
bad_whats <- c('est', 'dx.free', 'dx.all', 'std', 'std.lv', 'std.nox')
good_whats <- c('cov.lv', 'cor.lv', 'mean.lv', 'cov.ov', 'cor.ov', 'mean.ov', 'cov.all', 'cor.all', 'th')

# should return 2  for the HS data
test_what <- function(what) length(inspect(fit, what))

unlist(lapply(good_whats, test_what))
unlist(lapply(bad_whats, test_what))
```

I think it would be a quick fix. If returning one entry per subject seems like the correct behavior, just let me know and I'm happy to make the changes and submit a pull request.

**Edit.** Just as a note in case someone needs a workaround, you could use something like...

```
# flattened list with named entries for each component
est <- inspect(fit, 'est')
# vector of group labels 
g_lab <- inspect(fit, 'group.label')

# number of unique components (e.g. lambda, theta, psi, nu)
# this is necessary because some components will be omitted
# if something like meanstructure=FALSE is used when fitting
n_comp <- length(unique(names(est)))
# assumes that order of elements in est corresponds to group vector
g_est <- split(est, rep(g_lab, each=n_comp))

# can verify on HS example above
cov1 <- inspect(fit, 'cov.ov')[['Grant-White']]
cov2 <- with(g_est[['Grant-White']], lambda %*% psi %*% t(lambda) + theta)
all(cov1 == cov2)
```

**Comment by yrosseel** [comment]
Good point. There is a historical reason for this, but that does not change the fact that this is not consistent. I have changed this in dev 0.5-21. Per default, lavInspect() will now always return an entry per group (instead of a flattened list). This may have side-effects (even in other packages where they have been relying on the old behavior). So further testing is needed. lavTech (per default) still returns a flattened list (because this is how it is represented internally).
