### ISSUE TITLE
Export some internal functions?

### ISSUE THREAD

**Issue by JWiley** [yrosseel/lavaan#63]
For a variety of situations it can be helpful to get maximum likelihood estimates of means and covariance matrices.  lavaan can do this, but the functions are all internal and there is no convenient exported function to accomplish it.  I wonder if the internal functions could be exported, or alternately the function below perhaps added to lavaan (uses roxygen2 style documentation):

```r
#' Estimate the first and second moments
#'
#' This function relies on the \pkg{lavaan} package to use the
#' Expectation Maximization (EM) algorithm to estimate the first and
#' second moments (means and [co]variances) when there is missing data.
#'
#' @param data A data frame or an object coercable to a data frame.
#'   The means and covariances of all variables are estimated.
#' @param \dots Additional arguments passed on to the \code{estimate.moments.EM}
#'   function in \pkg{lavaan}. Note this is not an exported function.
#' @return A list containing the esimates from the EM algorithm.
#'   \item{mu}{A named vector of the means.}
#'   \item{sigma}{The covariance matrix.}
#' @seealso \code{\link{SEMSummary}}
#' @keywords multivariate
#' @importFrom lavaan lavaan
#' @export
#' @examples
#' # sample data
#' Xmiss <- as.matrix(iris[, -5])
#' # make 25% missing completely at random
#' set.seed(10)
#' Xmiss[sample(length(Xmiss), length(Xmiss) * .25)] <- NA
#' Xmiss <- as.data.frame(Xmiss)
#'
#' # true means and covariance
#' colMeans(iris[, -5])
#' # covariance with n - 1 divisor
#' cov(iris[, -5])
#'
#' # means and covariance matrix using list wise deletion
#' colMeans(na.omit(Xmiss))
#' cov(na.omit(Xmiss))
#'
#' # means and covariance matrix using EM
#' moments(Xmiss)
#' # clean up
#' rm(Xmiss)
moments <- function(data, ...) {
  if (!is.data.frame(data)) {
    data <- as.data.frame(data)
  }

  n <- colnames(data)
  X <- lavaan:::lav_data_full(data, ov.names = n, missing = "fiml")
  mpat <- lavaan:::getMissingPatternStats(X = X@X[[1L]], Mp = X@Mp[[1L]])
  moments <- lavaan:::estimate.moments.EM(X = X@X[[1L]], M = mpat, verbose=FALSE, ...)
  sigma <- moments$sigma
  dimnames(sigma) <- list(n, n)
  mu <- moments$mu
  names(mu) <- n

  return(list(mu = mu, sigma = sigma))
}
```

**Comment by yrosseel** [comment]
On 08/31/2016 03:21 AM, Joshua F. Wiley wrote:
> For a variety of situations it can be helpful to get maximum likelihood
> estimates of means and covariance matrices. lavaan can do this, but the
> functions are all internal and there is no convenient exported function
> to accomplish it.

I wish you asked me this before you uploaded your package to CRAN. How 
did you manage to circumvent the CRAN policies (where calling private 
functions using :::: are forbidden)?

Because I have already changed one of the internal functions you use 
(lavaan:::getMissingPatternStats, is now 
lavaan:::lav_samplestats_missing_patterns, with different arguments) in 
dev 0.5-21, I break your package, and as a result, I can no longer 
update (again due to CRAN policies: you shall not break somebody else's 
package).

Please remove these ::: calls from your package and resubmit, because it 
blocks the update of lavaan 0.5-21. As a simple alternative, you can use 
something along the lines of:

moments <- function(data) {
     fit <- lavCor(data, output = "fit", missing = "ml")
     lavInspect(fit, "sampstat.h1")
}

Yves.

**Comment by JWiley** [comment]
Well, I had asked but it was a very long time ago.  In regards to CRAN, ::: is not completely forbidden, though strongly strongly discouraged.

In any case, I have revised the function as suggested and just uploaded an updated version to CRAN along with some other additions.  I am getting 0 errors/warnings/notes from Rcmd check now, so I anticipate this will be accepted to CRAN shortly and no longer block the update of lavaan.

Thanks!

**Comment by yrosseel** [comment]
On 09/01/2016 08:30 AM, Joshua F. Wiley wrote:
> In any case, I have revised the function as suggested and just uploaded
> an updated version to CRAN along with some other additions. I am getting
> 0 errors/warnings/notes from Rcmd check now, so I anticipate this will
> be accepted to CRAN shortly and no longer block the update of lavaan.

Thanks a lot for your prompt reaction!

Yves.
