### ISSUE TITLE
Possible minor bug in lav_predict.R, lav_predict_eta_ebm

### ISSUE THREAD

**Issue by davidp6** [yrosseel/lavaan#64]
I may be mistaken, but it would appear that line 507 in lav_predict.R has a minor error. Line 507 reads:

`eta.i <- rep(as.numeric(NA), nfac2)`

but I think `nfac2` should actually be `nfac`. 

**Reason**: `nfac2` stores the number of factors plus number of `ov.y` dummy variables. `nfac` stores just the former. The vector `eta.i` should be the length of `nfac` at line 511, because it then goes on to add an extra value for each `ov.y` dummy in lines 511-514. If line 507 creates a vector of length `nfac2`, then lines 511-514 will end up creating a vector `eta.i` which is longer than the vector it replaces (`FS[[g]][i,]`) in line 516.

**Comment by yrosseel** [comment]
I think you may be right. I will investigate this further and report 
back here.

**Comment by yrosseel** [comment]
Fixed in dev 0.5-23
