### ISSUE TITLE
(minor) Error: summary(fit, rsquare=TRUE) 

### ISSUE THREAD

**Issue by akretzsch** [yrosseel/lavaan#74]
If you request R-Square values for a correlation without latent variables, you will get a rather cryptic error and no results at all. I guess a warning would be better:

```
model <- 'x1 ~~ x2'
fit <- cfa(model, data = HolzingerSwineford1939)
summary(fit, rsquare=TRUE)
```

Errror:
> Error: !is.null(pt2$lhs) ist nicht TRUE

If works fine with `summary(fit, rsquare=FALSE)`.

Version: lavaan_0.5-23.1097

**Comment by yrosseel** [comment]
Thanks. This will now work and generate a warning in 0.6-1.
