### ISSUE TITLE
user-supplied group.label argument returns error

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#77]
Hi Yves,

I'm copying a bug posted on the lavaan forum.  

```
HS.model <- ' visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '
fit <- cfa(HS.model, data=HolzingerSwineford1939,
           group = "school", group.label = c("Pasteur","Grant-White"))
```

On line 333 of lav_data.R, the user-supplied `group.label` is compared to an all lowercase version of the group labels, so `match()` returns `NA`.  I couldn't find `tolower(group.label)` anywhere, but the labels are already lowercase in the `lavoptions` argument of `lavData()`.

**Comment by yrosseel** [comment]
fixed in 0.6-1.1140
