### ISSUE TITLE
Constrain standardized loadings?

### ISSUE THREAD

**Issue by jgellar** [yrosseel/lavaan#80]
Hopefully a quick question:

Is it possible to constrain standardized loadings to be equal to one another in a CFA model?

My understanding is that this is not possible, but I wanted to double-check. Thanks in advance.

Jonathan

**Comment by TDJorgensen** [comment]
Since this is a question about using lavaan rather than a bug report, I posted a response on the lavaan forum where other users might also benefit from the discussion:

https://groups.google.com/d/msg/lavaan/LJ0iasC-3KM/WhqtflpiAwAJ

Terrence
