### ISSUE TITLE
No ability to fix composite loadings in group.equal

### ISSUE THREAD

**Issue by jebyrnes** [yrosseel/lavaan#83]
See __ for fill description

However, in looking through the code, in the portion of lav_partable_labels.R starting at 64 none of the options pertain to composite loadings. So, something like

```
        # LOADINGS
        if("composite_loadings" %in% group.equal)
            g1.flag[ partable$op == "<~" & partable$group == 1L  ] <- TRUE 
```

would seem to be in order.

There might also need to be a change in lav_partable.R around line 312 and lav_options.R around 204.

**Comment by yrosseel** [comment]
In 0.6-4, "composite.loadings" can be used in group.label=
