### ISSUE TITLE
Problem with mixing parameter labels and constraints

### ISSUE THREAD

**Issue by michaelhallquist** [yrosseel/lavaan#84]
Hi Yves,

I would like to identify a multiple-groups measurement invariance model (e.g., weak) using the 'unit variance identification' approach (aka standardized factors). In the multiple-groups case, all loadings are free parameters that are equated between groups. The factor variances are fixed to 1 in one group, but free in the others. I tried to specify this using a parameter vector that contains a 1 for one group, but a label for the other. This led lavaan to apply the label to both groups as an equality constraint. Syntax follows:

```
#trying to mix constraints and labels to achieve ULI in two groups
mmod_uvi <-'
  visual  =~ NA*x1 + x2 + x3
  textual =~ NA*x4 + x5 + x6
  speed   =~ NA*x7 + x8 + x9 

#does not work -- applies an equality constraint
visual ~~ c(1, v2)*visual
textual ~~ c(1, t2)*textual
speed ~~ c(1, s3)*speed
'

mweak_uvi_bad <- sem(mmod_uvi, data = HolzingerSwineford1939, std.lv=FALSE, group = "school", group.equal="loadings", meanstructure=TRUE)
```

Thanks for continuing to develop this excellent package!
Michael

**Comment by yrosseel** [comment]
Thanks Michael for the report.
This is not a 'bug' per se, but more something that is not implemented (yet?). You can not mix labels and constants. But you can write:

visual ~~ c(v1, v2)*visual + c(1,NA)*visual

So you can have the same lhs element multiple times, each one with its own set of modifiers. Here, the first one adds the labels, while the second one handles the constants.

**Comment by michaelhallquist** [comment]
Ah, thanks, I hadn't considered using different modifiers in separate terms! I'll use that for the time being. If you point me to the parser that determines the role of a given vector, I might be able to create a pull request that does checks on the terms to potentially allow mixing.
