### ISSUE TITLE
std.lv effects in multiple-groups analysis

### ISSUE THREAD

**Issue by michaelhallquist** [yrosseel/lavaan#85]
Hi Yves,

Related to the issue about unit variance identification in multiple groups, I noticed that std.lv=TRUE gives an odd behavior in multiple-groups analysis. Specifically, it sets the factor variances to 1 even when loadings are equated. A good default in this case might be to set variance to 1 in one group, but free in the others, per typical identification rules. Or maybe it's better just to warn the user about this behavior since it yields non-equivalent models in the multiple-groups case.

```
library(lavaan)
HS.model <- ' visual =~ x1 + x2 + x3
  textual =~ x4 + x5 + x6
  speed   =~ x7 + x8 + x9 
'

#these are not equivalent models because variances are not freed in the second group in the uvi model
mweak_uli <- sem(mmod_uvi, data = HolzingerSwineford1939, std.lv=FALSE, group = "school", group.equal="loadings", meanstructure=TRUE)            
mweak_uvi <- sem(mmod_uvi, data = HolzingerSwineford1939, std.lv=TRUE, group = "school", group.equal="loadings", meanstructure=TRUE)
```

Thanks!
Michael

**Comment by yrosseel** [comment]
Eventually, I did change this in 0.6-4.1417: in the multiple group setting when std.lv = TRUE and
group.equal contains "loadings", the latent variances are set to unity in the first group only.

Only then do we get the same results for the following three examples:

library(lavaan)
HS.model <- ' visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9
'
fit <- cfa(HS.model, data=HolzingerSwineford1939, meanstructure = TRUE,
           group = "school", group.equal = c("loadings"),
           std.lv = FALSE)
fit

fit1 <- cfa(HS.model, data=HolzingerSwineford1939, meanstructure = TRUE,
           group = "school", group.equal = c("loadings"),
           std.lv = TRUE)
fit1


fit2 <- cfa(HS.model, data=HolzingerSwineford1939, meanstructure = TRUE,
            group = "school", group.equal = c("loadings"),
            effect.coding = TRUE)
fit2

**Comment by michaelhallquist** [comment]
Great, thanks, Yves! This looks helpful to me in terms of unifying the defaults.

-Michael
