### ISSUE TITLE
anova() seems to call lavTestLRT() with wrong argument values

### ISSUE THREAD

**Issue by DaniMori** [yrosseel/lavaan#89]
When I call

`anova(nested.model, unconstrained.model, method = "satorra.bentler.2010")`

I receive the following error:

```Error in lav_test_diff_af_h1(m1 = m1, m0 = m0) : lavaan ERROR: unconstrained parameter set is not the same in m0 and m1```

It seems like lavTestLRT is being called with argument `method = "default"` for some reason.

I'm on lavaan version 0.5-23.1097.

My version info:
```
platform       x86_64-w64-mingw32
arch           x86_64
os             mingw32
system         x86_64, mingw32
status
major          3
minor          4.2
year           2017
month          09
day            28
svn rev        73368
language       R
version.string R version 3.4.2 (2017-09-28)
nickname       Short Summer
```

**Comment by TDJorgensen** [comment]
To make sure this is a current problem, does this error occur when you use the latest version of `lavaan`?
```
install.packages("lavaan", repos="http://www.da.ugent.be", type="source")
```
Regardless of the version, there is not enough information here (data and syntax) to reproduce the problem.  For instance, if your data are categorical, then `method = "satorra.bentler.2010"` might not be an option.

github is a great place to post bugs when you find them, or to make feature requests. But there is a general lavaan-users forum when you can post questions (and data/syntax) for help.
https://groups.google.com/d/forum/lavaan

**Comment by yrosseel** [comment]
This is not a bug, but an error message saying that the constrained model is not fully nested within the full model (in the parameter sense).
