### ISSUE TITLE
lavPredict from models with categorical variables

### ISSUE THREAD

**Issue by dmaltschul** [yrosseel/lavaan#92]
Hello,
I think I've found an issue in lavPredict(), where the function spits out the following error when factor variables are included in the model one predicts from:
```
Error in `[<-`(`*tmp*`, , ov.x.dummy.lv.idx, value = eXo) : 
  subscript out of bounds
```

If one changes the factor to a numeric, the error goes away and the function seems to operate normally. I have no idea why this happens or if the function is actually working as intended, but it would at very least be nice to note in the help file that factor data won't work if one wants to lavPredict.

(Thanks for all your hard work!)

**Comment by yrosseel** [comment]
Could you provide a small example? What do you mean with 'factor': an unordered variable? There should be no 'factors' in a SEM model. If the factors are exogenous, you should create (numeric) dummy variables. If they are endogenous, lavaan does not support them (and you have received a warning).

**Comment by dmaltschul** [comment]
I made an example (see below), but I think I see the issue. I tried this again with version 0.6 and a few things seem to have changed, but the documentation is clearer.
 
`HolzingerSwineford1939$sex = as.factor(HolzingerSwineford1939$sex)`

`HS.model <- ' visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6 + sex 
              speed   =~ x7 + x8 + x9 '`

`fit <- lavaan(HS.model, data=HolzingerSwineford1939,
              auto.var=TRUE, auto.fix.first=TRUE,
              auto.cov.lv.x=TRUE)`

`head(lavPredict(fit, type='lv'))
`

Doing this in v0.6 gives a different error:
`Error in lav_predict_fy_eta.i(lavmodel = lavmodel, lavdata = lavdata,  : 
  lavaan ERROR: unknown type: factor for variablesex 
`

As you can see, the factor in question is exogenous, and if one leaves the sex variable as numeric, there isn't any issue. The latest documentation is helpful in clarifying the best approach, though the only odd thing remaining is that the model can be fitted just fine with the variable set as a factor, and it only comes up as an issue when using methods like lavPredict. In my case, the data I originally had this trouble with had the factor variables already set, so I didn't think to change them to numerics from the outset.

**Comment by yrosseel** [comment]
Thanks for the example. In 0.6-2, including a factor will produce a fatal error. (Unless it is an exogenous variable with only 2 levels).

Yves.
