### ISSUE TITLE
NAs in scaled and robust CFI/TLI since version 0.6-1.1203

### ISSUE THREAD

**Issue by aneumann-science** [yrosseel/lavaan#95]
Dear all,

A colleague of mine noticed, that since version 0.6-1.1203 (perhaps also earlier) in some datasets the scaled and robust CFI/TLI values are missing. This bug seems to only appear with MLR, not with MLM. Below a reproducible example:

```
library(lavaan)

HS.model <- ' visual  =~ x1 + x2 + x3 
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '

fit <- cfa(HS.model, estimator = "MLR", data=HolzingerSwineford1939)

summary(fit, fit.measures=TRUE)

lavaan (0.6-1.1207) converged normally after  35 iterations

  Number of observations                           301

  Estimator                                         ML      Robust
  Model Fit Test Statistic                      85.306      80.890
  Degrees of freedom                                24          24
  P-value (Chi-square)                           0.000       0.000
  Scaling correction factor                                  1.055
    for the Yuan-Bentler correction

Model test baseline model:

  Minimum Function Test Statistic              918.852          NA
  Degrees of freedom                                36          36
  P-value                                        0.000          NA

User model versus baseline model:

  Comparative Fit Index (CFI)                    0.931          NA
  Tucker-Lewis Index (TLI)                       0.896          NA

  Robust Comparative Fit Index (CFI)                            NA
  Robust Tucker-Lewis Index (TLI)                               NA
```

This does not occur with MLM:

```
HS.model <- ' visual  =~ x1 + x2 + x3 
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '

fit <- cfa(HS.model, estimator = "MLM", data=HolzingerSwineford1939)

summary(fit, fit.measures=TRUE)

lavaan (0.6-1.1207) converged normally after  35 iterations

  Number of observations                           301

  Estimator                                         ML      Robust
  Model Fit Test Statistic                      85.306      80.872
  Degrees of freedom                                24          24
  P-value (Chi-square)                           0.000       0.000
  Scaling correction factor                                  1.055
    for the Satorra-Bentler correction

Model test baseline model:

  Minimum Function Test Statistic              918.852     789.298
  Degrees of freedom                                36          36
  P-value                                        0.000       0.000

User model versus baseline model:

  Comparative Fit Index (CFI)                    0.931       0.925
  Tucker-Lewis Index (TLI)                       0.896       0.887

  Robust Comparative Fit Index (CFI)                         0.932
  Robust Tucker-Lewis Index (TLI)                            0.897

```

**Comment by yrosseel** [comment]
On 03/28/2018 06:04 PM, Alexander Neumann wrote:
> A colleague of mine noticed, that since version 0.6-1.1203 (perhaps also 
> earlier), in some datasets the scaled and robust CFI/TLI values are 
> missing. This seems to only appear with MLR, not with MLM.

Confirmed.

The very short answer: use option h1.information = "unstructured"

The long answer:

This is a byproduct of a change (that is still under evaluation, so 
perhaps this will change again) made a few commits ago related to the 
way we compute the information matrix for the unrestricted model (h1), 
which is an ingredient of the MLR test statistic.

There are two choices: "structured" and "unstructured" (set by the 
h1.information argument). Structured means that the 'sigma' in the 
formula is replaced by the model-implied sigma. Unstructured means that 
'sigma' is replaced by the sample-based covariance matrix.

Preliminary simulations have shown me that 'structured' usually works 
best. The exception are really badly specified models, for example, the 
independence model. For those models, things go wrong, ending up in 
'NA'. And this affects CFI/TLI.

One way out might be to 'always' use 'unstructured' for the independence 
model, but that feels somewhat inconsistent.

I will further evaluate this, and decide what to do before 0.6 gets 
released.

Yves.

**Comment by aneumann-science** [comment]
Thanks for the explanation! Perhaps a compromise would be to give a warning if NA occur, suggesting to try "h1.information = "unstructured""?

**Comment by yrosseel** [comment]
For 0.6-1, I decided to keep the 'old' (0.5) approach. This implies (by default) MLR will use test = "yuan.bentler.mplus". Further simulation work is needed, and this may change again in a next update, but not in 0.6-1.
