### ISSUE TITLE
lavPredict w/newdata outputting old data from model fitting?

### ISSUE THREAD

**Issue by jmobrien** [yrosseel/lavaan#97]
adding new data to the lavPredict function (using newdata =) still outputs the old data as if I had just called lavPredict on the model object alone (outputs match, same length, predictions from new data should have been much shorter in length).  

If I'm not missing something, problem may be on line 89--swapping out lavdata = lavdata for lavdata = newData (defined on line 63) while in debug mode appears to produce output that seems okay (correct length, missing in rows where indicator data is entirely missing, though I haven't dug into lav_predict_eta to know if that's doing what I expect)

**Comment by yrosseel** [comment]
On 04/10/2018 08:34 PM, jmobrien wrote:
> adding new data to the lavPredict function (using newdata =) still 
> outputs the old data 
I have trouble reproducing this. Can you provide a reproducible example?

This works (in both 0.5-23 and 0.6-1):

library(lavaan)
example(cfa)
newData <- HolzingerSwineford1939[5:10, lavNames(fit)]
lavPredict(fit, newdata = newData)

gives

      visual textul  speed
[1,] -0.416 -0.122  0.194
[2,]  0.023 -1.330  0.709
[3,] -0.985  0.658  0.044
[4,]  0.107 -0.105 -0.532
[5,] -0.254  0.404  0.200
[6,] -1.054  0.093 -0.567


I also tried this with categorical data, and it also worked. But perhaps 
there is another setting that fails to work.

Yves.

**Comment by jmobrien** [comment]
Thanks!  I'm not surprised you couldn't replicate; seems unlikely a true
bug would have gone unnoticed in such central code that's been stable for
this long.

Let me see if I can re-create it, and if so I'll try to put together
something shareable from the (somewhat sensitive) data I have.  If not I'll
try and respond explaining my error.  Hopefully soon, but it may be a few
days.

Joseph O'Brien, M.A.
Adolescent Development Research Group
Department of Psychology
University of Texas at Austin
joseph.obrien@utexas.edu

**Comment by yrosseel** [comment]
As I never recieved a reprex, I will close this.
